<?php
declare(strict_types=1);
// Copy to config.local.php. Never commit the local config or database.
return [
    'username' => '',
    'password_hash' => '', // Generate with setup.php or password_hash(). No default password.
    'secret' => '', // At least 32 random characters; generated by setup.php.
    'storage' => '/absolute/path/outside/public_html/webstats-data',
    'timezone' => 'America/New_York',
    'origins' => [
        'https://jasr.me' => 'jasr.me',
        'https://www.jasr.me' => 'jasr.me',
        'https://jasonlamb.me' => 'jasonlamb.me',
        'https://www.jasonlamb.me' => 'jasonlamb.me',
        'https://justjason.fyi' => 'justjason.fyi',
        'https://www.justjason.fyi' => 'justjason.fyi',
        'https://jasrasr.github.io' => 'jasrasr.github.io',
    ],
    'excluded_paths' => ['/github/webstats/', '/wp-admin/', '/wp-login.php'],
    'retention_days' => 180,
    'events_per_ip_per_minute' => 120,
    'events_per_day' => 10000,
];
