<?php
// ============================================================================
// File: manage_stations.php
// Purpose: Admin UI for editing and deleting saved fuel-station profiles
// Revision: 1.0.0
// Author: Jason Lamb
// ============================================================================

error_reporting(E_ALL);ini_set('display_errors',1);if(session_status()===PHP_SESSION_NONE)session_start();require_once __DIR__.'/device_init.php';if(!$isAdminTrusted)die('<h2>Access denied.</h2>');
$stationsFile=__DIR__.'/stations.json';$data=['brands'=>[],'locations'=>[]];if(file_exists($stationsFile)){$d=json_decode(file_get_contents($stationsFile),true);if(is_array($d))$data=array_merge($data,$d);}if(!is_array($data['locations']??null))$data['locations']=[];
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Manage Fuel Stations</title><style>body{font-family:sans-serif;max-width:1200px;margin:auto;padding:1rem}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.6rem}.card{border:1px solid #ddd;border-radius:8px;padding:1rem;margin:1rem 0}.card input{width:100%;padding:.4rem;box-sizing:border-box}.actions{margin-top:.8rem;display:flex;gap:.5rem}.save{background:#28a745;color:#fff;border:0;padding:.5rem .8rem;border-radius:4px}.delete{background:#dc3545;color:#fff;border:0;padding:.5rem .8rem;border-radius:4px}.msg{padding:.6rem;border-radius:6px;background:#eef;margin-bottom:1rem}.note{font-size:.82rem;color:#666}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head><body>
<h2>Manage Saved Fuel Stations</h2><p><a href="admin.php">← Back to Admin</a></p><div id="msg" class="msg" style="display:none"></div>
<?php if(empty($data['locations'])):?><p>No saved station profiles yet. Confirm a nearby station from a fuel-entry page and it will appear here.</p><?php endif;?>
<?php foreach($data['locations'] as $loc):$id=$loc['id']??'';if($id==='')continue;?><div class="card" data-id="<?=htmlspecialchars($id)?>"><div class="grid"><label>Brand<input data-field="brand" value="<?=htmlspecialchars($loc['brand']??'')?>"></label><label>Name<input data-field="name" value="<?=htmlspecialchars($loc['name']??'')?>"></label><label>Nickname<input data-field="nickname" value="<?=htmlspecialchars($loc['nickname']??'')?>"></label><label>City<input data-field="city" value="<?=htmlspecialchars($loc['city']??'')?>"></label><label>Street / Address<input data-field="street" value="<?=htmlspecialchars($loc['street']??'')?>"></label><label>Intersection<input data-field="intersection" value="<?=htmlspecialchars($loc['intersection']??'')?>"></label><label>Latitude<input data-field="latitude" type="number" step="0.000001" value="<?=htmlspecialchars($loc['latitude']??'')?>"></label><label>Longitude<input data-field="longitude" type="number" step="0.000001" value="<?=htmlspecialchars($loc['longitude']??'')?>"></label></div><p class="note">Profile ID: <?=htmlspecialchars($id)?><?php if(!empty($loc['candidate_id'])):?> · Source: <?=htmlspecialchars($loc['candidate_id'])?><?php endif;?></p><div class="actions"><button class="save" type="button">Save</button><button class="delete" type="button">Delete</button></div></div><?php endforeach;?>
<script>const msg=document.getElementById('msg');function show(m,ok=true){msg.textContent=m;msg.style.display='block';msg.style.background=ok?'#d4edda':'#f8d7da'}document.querySelectorAll('.card').forEach(card=>{card.querySelector('.save').onclick=async()=>{const p=new URLSearchParams({action:'save_profile',profile_id:card.dataset.id,source:'manual_admin'});card.querySelectorAll('[data-field]').forEach(el=>p.set(el.dataset.field,el.value));try{const r=await fetch('station_api.php',{method:'POST',body:p}),d=await r.json();if(d.error)throw new Error(d.error);show('Station profile saved.')}catch(e){show(e.message,false)}};card.querySelector('.delete').onclick=async()=>{if(!confirm('Delete this saved station profile? Existing fuel entries keep their stored station data.'))return;try{const r=await fetch('station_api.php',{method:'POST',body:new URLSearchParams({action:'delete_profile',profile_id:card.dataset.id})}),d=await r.json();if(d.error)throw new Error(d.error);card.remove();show('Station profile deleted.')}catch(e){show(e.message,false)}}});</script>
</body></html>
