<?php
// ============================================================================
// File: view_stats.php
// Purpose: Fuel, MPG, price, and station analytics for one vehicle
// Revision: 1.1
// Author: Jason Lamb
// ============================================================================

error_reporting(E_ALL);ini_set('display_errors',1);if(session_status()===PHP_SESSION_NONE)session_start();
$plate=preg_replace('/[^A-Z0-9]/','',strtoupper(trim($_GET['plate']??'')));if($plate==='')die('<h2>No license plate specified.</h2>');$logFile=__DIR__."/logs/{$plate}.json";if(!file_exists($logFile))die('<h2>No log found.</h2>');$data=json_decode(file_get_contents($logFile),true);if(!is_array($data)||!count($data))die('<h2>No entries found.</h2>');
$labels=[];$prices=[];$miles=[];$tips=[];$fillTypes=[];$totalGallons=0;$totalCost=0;$weightedMiles=0;$weightedGallons=0;$stationStats=[];
foreach($data as $e){$labels[]=$e['date']??'—';$prices[]=(float)($e['price_per_gallon']??0);$miles[]=(float)($e['miles']??0);$tips[]=$e['submitted_et']??'N/A';$fillTypes[]=strtolower((string)($e['fill_type']??'full'));$g=(float)($e['gallons']??0);$c=(float)($e['total_cost']??0);$totalGallons+=$g;$totalCost+=$c;if(($e['mpg_miles']??0)>0&&($e['mpg_gallons']??0)>0){$weightedMiles+=(float)$e['mpg_miles'];$weightedGallons+=(float)$e['mpg_gallons'];}$brand=trim((string)($e['station_brand']??''));if($brand!==''){$key=strtolower($brand);if(!isset($stationStats[$key]))$stationStats[$key]=['brand'=>$brand,'fills'=>0,'gallons'=>0,'cost'=>0,'prices'=>[]];$stationStats[$key]['fills']++;$stationStats[$key]['gallons']+=$g;$stationStats[$key]['cost']+=$c;if(($e['price_per_gallon']??0)>0)$stationStats[$key]['prices'][]=(float)$e['price_per_gallon'];}}
function medianVal($v){sort($v,SORT_NUMERIC);$n=count($v);if(!$n)return 0;$m=intdiv($n,2);return$n%2?$v[$m]:($v[$m-1]+$v[$m])/2;}
$avgMPG=$weightedGallons>0?round($weightedMiles/$weightedGallons,2):0;$costPerMile=$weightedMiles>0?round($totalCost/$weightedMiles,3):0;
foreach($stationStats as &$s){$s['avg_price']=count($s['prices'])?array_sum($s['prices'])/count($s['prices']):0;$s['median_price']=medianVal($s['prices']);}unset($s);usort($stationStats,fn($a,$b)=>$b['fills']<=>$a['fills']);
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Stats - <?=htmlspecialchars($plate)?></title><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><style>body{font-family:sans-serif;max-width:1100px;margin:auto;padding:1rem}canvas{margin:1rem 0 2rem}a{color:#007bff;text-decoration:none}.cards{display:flex;gap:.8rem;flex-wrap:wrap}.card{border:1px solid #ddd;border-radius:8px;padding:.8rem 1rem;min-width:150px}.card b{display:block;font-size:1.2rem}table{width:100%;border-collapse:collapse;margin-top:1rem}th,td{border:1px solid #ccc;padding:.5rem;text-align:left}th{background:#f2f2f2}.note{color:#666;font-size:.85rem}</style></head><body>
<h2>Stats — <?=htmlspecialchars($plate)?></h2><div class="cards"><div class="card"><span>Tracked gallons</span><b><?=number_format($totalGallons,3)?></b></div><div class="card"><span>Fuel cost</span><b>$<?=number_format($totalCost,2)?></b></div><div class="card"><span>Full-to-full MPG</span><b><?=number_format($avgMPG,2)?></b></div><div class="card"><span>Cost/mile</span><b>$<?=number_format($costPerMile,3)?></b></div></div><p class="note">MPG uses completed full-to-full intervals. Partial fills contribute their gallons to the next completed interval rather than generating a standalone MPG.</p>
<h3>Price per Gallon Over Time</h3><canvas id="priceChart" height="120"></canvas><h3>Miles Between Fuel Events</h3><canvas id="milesChart" height="120"></canvas>
<?php if($stationStats):?><h3>Station Price Comparison</h3><table><thead><tr><th>Station</th><th>Fill Events</th><th>Gallons</th><th>Spend</th><th>Avg $/gal</th><th>Median $/gal</th></tr></thead><tbody><?php foreach($stationStats as $s):?><tr><td><?=htmlspecialchars($s['brand'])?></td><td><?=$s['fills']?></td><td><?=number_format($s['gallons'],3)?></td><td>$<?=number_format($s['cost'],2)?></td><td>$<?=number_format($s['avg_price'],3)?></td><td>$<?=number_format($s['median_price'],3)?></td></tr><?php endforeach;?></tbody></table><?php endif;?>
<?php include 'menu.php';?>
<script>const labels=<?=json_encode($labels)?>,prices=<?=json_encode($prices,JSON_NUMERIC_CHECK)?>,miles=<?=json_encode($miles,JSON_NUMERIC_CHECK)?>,tips=<?=json_encode($tips)?>,fillTypes=<?=json_encode($fillTypes)?>;new Chart(document.getElementById('priceChart'),{type:'line',data:{labels,datasets:[{label:'Price per Gallon ($)',data:prices,borderWidth:2,tension:.3,fill:false}]},options:{plugins:{tooltip:{callbacks:{afterLabel:c=>`${fillTypes[c.dataIndex]==='partial'?'Partial fill':'Full fill'} · ${tips[c.dataIndex]}`}}},scales:{y:{beginAtZero:false}}}});new Chart(document.getElementById('milesChart'),{type:'bar',data:{labels,datasets:[{label:'Miles since previous fuel event',data:miles,borderWidth:1}]},options:{plugins:{tooltip:{callbacks:{afterLabel:c=>`${fillTypes[c.dataIndex]==='partial'?'Partial fill':'Full fill'} · ${tips[c.dataIndex]}`}}},scales:{y:{beginAtZero:true}}}});</script></body></html>
