<?php
// ============================================================================
// File: view_map.php
// Purpose: Display and filter an interactive map of fuel stops
// Revision: 1.1.0
// Author: Jason Lamb
// ============================================================================

error_reporting(E_ALL);ini_set('display_errors',1);if(session_status()===PHP_SESSION_NONE)session_start();
$plate=preg_replace('/[^A-Z0-9]/','',strtoupper(trim($_GET['plate']??'')));if($plate==='')die('<h2>No license plate specified.</h2>');$logFile=__DIR__."/logs/{$plate}.json";if(!file_exists($logFile))die('<h2>No log found.</h2>');$data=json_decode(file_get_contents($logFile),true);if(!is_array($data))die('<h2>Fuel log is unreadable.</h2>');
$points=[];$brands=[];foreach($data as $e){if(!isset($e['latitude'],$e['longitude']))continue;$lat=(float)$e['latitude'];$lon=(float)$e['longitude'];if($lat<-90||$lat>90||$lon<-180||$lon>180)continue;$brand=trim((string)($e['station_brand']??''));if($brand!=='')$brands[strtolower($brand)]=$brand;$loc=trim((string)($e['station_location_label']??''));$station=$brand;if($loc!=='')$station=$station!==''?$station.' — '.$loc:$loc;$points[]=['lat'=>$lat,'lon'=>$lon,'date'=>$e['date']??'','station'=>$station,'brand'=>$brand,'stationId'=>$e['station_location_id']??'','gallons'=>$e['gallons']??null,'price'=>$e['price_per_gallon']??null,'total'=>$e['total_cost']??null,'fillType'=>strtolower((string)($e['fill_type']??'full'))==='partial'?'Partial':'Full','mpg'=>$e['mpg']??null,'comment'=>$e['comment']??'','source'=>$e['location_source']??''];}natcasesort($brands);
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Fuel Stop Map - <?=htmlspecialchars($plate)?></title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><style>body{font-family:sans-serif;max-width:1200px;margin:auto;padding:1rem}#map{height:70vh;min-height:420px;border:1px solid #ccc;border-radius:8px;margin-top:1rem}.note{color:#666;font-size:.9rem}.filters{display:flex;gap:.6rem;flex-wrap:wrap;align-items:end;padding:.7rem;background:#f6f6f6;border-radius:8px}.filters label{font-size:.82rem;color:#444}.filters input,.filters select{display:block;padding:.4rem;margin-top:.2rem}a{color:#007bff;text-decoration:none}</style></head><body>
<h2>Fuel Stop Map — <?=htmlspecialchars($plate)?></h2><p class="note">Shows entries with saved coordinates from GPS, photo EXIF, or saved station profiles.</p><div class="filters"><label>From<input type="date" id="fromDate"></label><label>To<input type="date" id="toDate"></label><label>Station Brand<select id="brandFilter"><option value="">All brands</option><?php foreach($brands as $b):?><option value="<?=htmlspecialchars($b)?>"><?=htmlspecialchars($b)?></option><?php endforeach;?></select></label><label>Fill Type<select id="fillFilter"><option value="">All fills</option><option>Full</option><option>Partial</option></select></label><button id="clearFilters" type="button">Clear</button></div><div id="map"></div><?php include 'menu.php';?>
<script>const points=<?=json_encode($points,JSON_UNESCAPED_SLASHES|JSON_NUMERIC_CHECK)?>;const map=L.map('map');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);const layer=L.layerGroup().addTo(map);function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function render(){layer.clearLayers();const from=document.getElementById('fromDate').value,to=document.getElementById('toDate').value,brand=document.getElementById('brandFilter').value.toLowerCase(),fill=document.getElementById('fillFilter').value;const bounds=[];points.filter(p=>(!from||p.date>=from)&&(!to||p.date<=to)&&(!brand||String(p.brand).toLowerCase()===brand)&&(!fill||p.fillType===fill)).forEach(p=>{const m=L.marker([p.lat,p.lon]).addTo(layer);bounds.push([p.lat,p.lon]);m.bindPopup(`<b>${esc(p.date)}</b>${p.station?`<br><b>Station:</b> ${esc(p.station)}`:''}<br><b>Fill:</b> ${esc(p.fillType)}<br><b>Gallons:</b> ${esc(p.gallons)}<br><b>Price:</b> $${esc(p.price)}<br><b>Total:</b> $${esc(p.total)}<br><b>MPG:</b> ${p.mpg!==null&&p.mpg!==''?esc(p.mpg):'pending / not applicable'}${p.comment?`<br><b>Comment:</b> ${esc(p.comment)}`:''}`)});if(bounds.length)map.fitBounds(bounds,{padding:[30,30],maxZoom:15});else map.setView([39.5,-98.35],4)}['fromDate','toDate','brandFilter','fillFilter'].forEach(id=>document.getElementById(id).addEventListener('change',render));document.getElementById('clearFilters').onclick=()=>{['fromDate','toDate','brandFilter','fillFilter'].forEach(id=>document.getElementById(id).value='');render()};render();</script></body></html>
