<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
require dirname(__DIR__) . '/lib.php';
$checks = 0;
function check(bool $ok, string $message): void { global $checks; $checks++; if (!$ok) throw new Exception($message); }
function rejects(callable $fn, int $code): void { try { $fn(); } catch (RuntimeException $e) { check($e->getCode() === $code, $e->getMessage()); return; } throw new Exception('Expected rejection.'); }
$r = gb_new(['title' => 'Test']);
$host = ['host' => $r['host']];
function action(string $name, array $input = []): array { global $r, $host; return gb_apply($r, $name, $input + $host + ['operation' => gb_token()]); }
$one = gb_token(); $two = gb_token(); $other = gb_token();
action('join', ['key'=>$r['teams'][0]['join'], 'device'=>$one]);
action('join', ['key'=>$r['teams'][0]['join'], 'device'=>$two]);
action('join', ['key'=>$r['teams'][1]['join'], 'device'=>$other]);
rejects(fn()=>action('join',['key'=>$r['teams'][1]['join'],'device'=>$one]),409);
rejects(fn()=>gb_apply($r,'arm',['operation'=>gb_token()]),403);
$v = gb_view($r, []);
check(!isset($v['host'], $v['teamLinks'], $v['devices'], $v['ballots']), 'Private room data leaked');
check(!isset($v['teams'][0]['join']), 'Team invitation leaked');
rejects(fn()=>action('buzz',['device'=>$one,'round'=>0]),409);
action('arm',['duration'=>15]);
rejects(fn()=>action('buzz',['device'=>$one,'round'=>1]),409);
$r['openAt'] = microtime(true)-1;
action('buzz',['device'=>$one,'round'=>1]);
action('buzz',['device'=>$two,'round'=>1]);
action('buzz',['device'=>$other,'round'=>1]);
check(count($r['buzzes'])===2,'Same team counted twice');
check(gb_ranking($r)[0]['team']===0,'Incorrect ranking');
rejects(fn()=>action('award',['team'=>0,'round'=>1]),422);
action('closeBuzz',['round'=>1]);
rejects(fn()=>action('buzz',['device'=>$one,'round'=>1]),409);
action('award',['team'=>0,'round'=>1]);
action('award',['team'=>0,'round'=>1]);
check($r['teams'][0]['score']===1,'Double award');
action('arm',['duration'=>10]);
rejects(fn()=>action('buzz',['device'=>$one,'round'=>1]),409);
check(count($r['buzzes'])===0,'Old buzz carried over');
rejects(fn()=>action('question',['question'=>0]),422);
$voter=gb_token();$answers=array_fill(0,10,'a');
action('vote',['voter'=>$voter,'answers'=>$answers]);
action('vote',['voter'=>$voter,'answers'=>$answers]);
check(count($r['ballots'])===1,'Duplicate survey');
rejects(fn()=>action('vote',['voter'=>$voter,'answers'=>array_fill(0,10,'b')]),409);
action('vote',['voter'=>gb_token(),'answers'=>array_fill(0,10,'b')]);
action('vote',['voter'=>gb_token(),'answers'=>$answers]);
check(gb_view($r,[])['results']===null,'Survey totals leaked');
action('closeSurvey');
rejects(fn()=>action('vote',['voter'=>gb_token(),'answers'=>$answers]),409);
action('question',['question'=>0]);
action('predict',['device'=>$one,'question'=>0,'answer'=>'a']);
rejects(fn()=>action('predict',['device'=>$two,'question'=>0,'answer'=>'b']),409);
action('predict',['device'=>$other,'question'=>0,'answer'=>'b']);
check(gb_view($r,[])['predictions']===null,'Predictions leaked before reveal');
check(gb_view($r,[])['results']===null,'Results leaked before reveal');
action('reveal',['question'=>0]);
check(gb_view($r,[])['results']['a']===2,'Vote counts incorrect');
check($r['teams'][0]['score']===2 && $r['teams'][1]['score']===0,'Majority scoring incorrect');
action('reveal',['question'=>0]);
check($r['teams'][0]['score']===2,'Reveal scored twice');
rejects(fn()=>action('predict',['device'=>$other,'question'=>0,'answer'=>'a']),409);
action('question',['question'=>1]);
rejects(fn()=>action('predict',['device'=>$one,'question'=>0,'answer'=>'a']),409);
$r['ballots']=[$voter=>$answers,gb_token()=>array_fill(0,10,'b')];
action('predict',['device'=>$one,'question'=>1,'answer'=>'a']);
action('predict',['device'=>$other,'question'=>1,'answer'=>'b']);
action('reveal',['question'=>1]);
check($r['teams'][0]['score']===3 && $r['teams'][1]['score']===1,'Tie scoring incorrect');
$op=gb_token();action('adjust',['team'=>0,'delta'=>1,'operation'=>$op]);action('adjust',['team'=>0,'delta'=>1,'operation'=>$op]);
check($r['teams'][0]['score']===4,'Operation replay scored twice');
$config=['data_dir'=>sys_get_temp_dir().'/gb-test-'.bin2hex(random_bytes(6))];
gb_room($config,$r['id'],fn(&$stored)=>[], $r);
$loaded=gb_room($config,$r['id'],fn(&$stored)=>gb_view($stored,[]));
check($loaded['title']==='Test','Storage round trip');
check(str_starts_with(file_get_contents($config['data_dir'].'/'.$r['id'].'.php'), '<?php exit; ?>'), 'Missing storage guard');
foreach (glob($config['data_dir'].'/*') as $file) unlink($file); rmdir($config['data_dir']);
echo "Passed $checks game assertions.\n";
