<?php
require __DIR__ . '/lib.php';
if (!admin_logged_in()) { header('Location: admin.php'); exit; }
$code = clean_code((string)($_GET['code'] ?? ''));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Khootish Host</title><link rel="stylesheet" href="assets/app.css"></head><body><main class="shell"><div class="topbar"><div><h1>Khootish Host</h1><div class="code"><?=htmlspecialchars($code)?></div></div><div class="row"><a class="button secondary" href="admin.php">All games</a><a class="button secondary" target="_blank" href="display.php?code=<?=urlencode($code)?>">Open display</a></div></div><section class="card"><h2 id="title">Loading game…</h2><p id="phase" class="status"></p><div id="lobby"><div class="topbar"><h3>Host lobby</h3><span class="pill light-pill" id="teamCount">0 teams</span></div><div id="teams"></div></div><div class="row"><button id="start">Start next question</button><button id="results" class="secondary">Show results now</button><button id="finish" class="danger">Finish game</button><button id="replay" class="secondary">Archive and replay same code</button></div><div id="answerProgress" class="answer-progress hidden"></div><h3>Leaderboard</h3><div id="leaders"></div></section></main><script src="assets/app.js"></script><script>
const code=<?=json_encode($code)?>;let game=null;
const $=id=>document.getElementById(id);
function renderLobby(){const players=game.players;$('teamCount').textContent=`${players.length} team${players.length===1?'':'s'}`;$('teams').innerHTML=players.length?players.map(p=>`<div class="lobby-team"><span><i class="swatch" style="background:${p.color}"></i><strong>${escapeHtml(p.team_name)}</strong></span><div class="row"><button class="secondary small-button" data-rename="${escapeHtml(p.id)}" data-name="${escapeHtml(p.team_name)}">Rename</button><button class="danger small-button" data-remove="${escapeHtml(p.id)}" data-name="${escapeHtml(p.team_name)}">Remove</button></div></div>`).join(''):'<p class="muted">Waiting for teams to join…</p>';document.querySelectorAll('[data-rename]').forEach(b=>b.onclick=async()=>{const name=prompt('Rename team:',b.dataset.name);if(name===null)return;try{await api('rename_team',{code,player_id:b.dataset.rename,team_name:name});poll()}catch(e){alert(e.message)}});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{if(!confirm(`Remove ${b.dataset.name}?`))return;try{await api('remove_team',{code,player_id:b.dataset.remove});poll()}catch(e){alert(e.message)}})}
async function poll(){try{const r=await fetch(`api.php?action=state&code=${encodeURIComponent(code)}`,{cache:'no-store'}),j=await r.json();if(!j.ok)throw new Error(j.error);game=j.game;$('title').textContent=game.title;const answered=game.players.filter(p=>p.answered_current).length;$('phase').textContent=`Phase: ${game.phase} • Question ${game.question_number} of ${game.question_count} • ${game.players.length} teams${game.phase==='question'?` • ${answered}/${game.players.length} answered`:''}`;$('lobby').classList.toggle('hidden',game.phase!=='lobby');if(game.phase==='lobby')renderLobby();$('answerProgress').classList.toggle('hidden',game.phase!=='question');if(game.phase==='question')$('answerProgress').innerHTML=`<strong>${answered} of ${game.players.length}</strong> teams have answered.`;$('leaders').innerHTML=renderLeaderboard(game.players,game.players.length);$('start').disabled=game.phase==='question'||game.question_number>=game.question_count||game.players.length===0;$('start').textContent=game.phase==='lobby'?'Start first question':'Start next question';$('results').disabled=game.phase!=='question';$('finish').disabled=game.phase==='finished'}catch(e){$('phase').textContent=e.message}}
$('start').onclick=async()=>{try{await api('start_question',{code});poll()}catch(e){alert(e.message)}};$('results').onclick=async()=>{try{await api('show_results',{code});poll()}catch(e){alert(e.message)}};$('finish').onclick=async()=>{if(!confirm('Finish and archive this game?'))return;try{await api('finish_game',{code});poll()}catch(e){alert(e.message)}};$('replay').onclick=async()=>{if(!confirm(`Archive this game and start a fresh lobby using ${code}?`))return;try{await api('replay_game',{code});poll()}catch(e){alert(e.message)}};poll();setInterval(poll,1000);
</script></body></html>
