<?php $code = strtoupper(preg_replace('/[^A-Z0-9]/','',$_GET['code'] ?? '')); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Play Khootish</title><link rel="stylesheet" href="assets/app.css"></head><body><main class="shell"><div class="topbar"><h1>Khootish</h1><span class="pill">Game <?=htmlspecialchars($code)?></span></div><section class="card" id="screen"><p class="status">Connecting…</p></section></main><script src="assets/app.js"></script><script>
const code=<?=json_encode($code)?>;let game=null, answered=false, offset=0, questionId=null;
async function poll(){try{const r=await fetch(`api.php?action=state&code=${encodeURIComponent(code)}`,{cache:'no-store'});const j=await r.json();if(!j.ok)throw new Error(j.error);game=j.game;offset=game.server_time-Date.now()/1000;if(game.question?.id!==questionId){questionId=game.question?.id||null;answered=false}render()}catch(e){document.getElementById('screen').innerHTML=`<p class="status wrong">${escapeHtml(e.message)}</p>`}}
function render(){const s=document.getElementById('screen');if(game.phase==='lobby'){s.innerHTML=`<h2>You're in.</h2><p class="status">Waiting for the host to begin.</p><h3>Teams</h3>${renderLeaderboard(game.players)}`;return}if(game.phase==='question'){const q=game.question;const mine=game.players.find(p=>p.answered_current);if(mine)answered=true;s.innerHTML=`<div class="timer" id="timer">30</div><div class="progress"><div id="bar"></div></div><h2 class="question">${escapeHtml(q.text)}</h2><div class="answer-grid">${q.choices.map((c,i)=>`<button class="answer" data-i="${i}" ${answered?'disabled':''}>${escapeHtml(c)}</button>`).join('')}</div><p id="answerStatus" class="status ${answered?'':'hidden'}">${answered?'Answer locked in.':''}</p>`;s.querySelectorAll('.answer').forEach(b=>b.onclick=()=>submitAnswer(+b.dataset.i));tick();return}answered=false;if(game.phase==='results'){const q=game.question;s.innerHTML=`<h2 class="question">${escapeHtml(q.text)}</h2><p class="status correct">Correct answer: ${escapeHtml(q.choices[q.correct_index])}</p><h3>Current ranking</h3>${renderLeaderboard(game.players)}`;return}s.innerHTML=`<h2>Final ranking</h2>${renderLeaderboard(game.players,game.players.length)}`}
function tick(){if(!game||game.phase!=='question')return;const left=Math.max(0,game.ends_at-(Date.now()/1000+offset));const t=document.getElementById('timer'),b=document.getElementById('bar');if(t)t.textContent=Math.ceil(left);if(b)b.style.width=`${left/game.duration*100}%`;requestAnimationFrame(tick)}
async function submitAnswer(choice){if(answered)return;answered=true;document.querySelectorAll('.answer').forEach(b=>b.disabled=true);try{const r=await api('answer',{code,choice});const e=document.getElementById('answerStatus');e.textContent=r.result.correct?`Correct — ${r.result.points} points`:'Answer locked in.';e.className='status '+(r.result.correct?'correct':'');game=r.game}catch(err){answered=false;alert(err.message)}}
poll();setInterval(poll,1000);
</script></body></html>
