<?php
header('Cache-Control: no-store');
header('Referrer-Policy: no-referrer');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'self'; form-action 'self'");
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#101326"><title>Game Buzzer</title><link rel="stylesheet" href="style.css"></head>
<body><header><a href="./" class="brand">GAME <strong>BUZZER</strong></a><span id="connection" role="status">Ready to play</span></header>
<main><div id="notice" role="alert" hidden></div>
<section id="welcome" class="panel"><p class="eyebrow">SIX TEAMS. ONE ROOM. BIG ENERGY.</p><h1>Who’s got it?</h1><p class="intro">A giant team buzzer. A room full of opinions. Two ways to play.</p>
<form id="create"><label>Game name<input name="title" value="Battle of the Grades" required maxlength="80"></label><label>Room creation password<input name="password" type="password" required autocomplete="current-password"></label>
<details><summary>Edit the 10 arrival questions</summary><p>One question per line: Question | Answer A | Answer B</p><textarea id="questions" rows="12" aria-label="Ten survey questions"></textarea></details><button>Create game</button></form>
<p class="muted">Leaders and students: open the invitation link from your host. Hosts: see <a href="README.md">setup instructions</a>. No accounts or student names needed.</p></section>
<section id="game" hidden><div class="heading"><div><p class="eyebrow" id="roleLabel"></p><h1 id="gameTitle"></h1></div><button id="fullscreen" class="secondary">Full screen</button></div>
<section id="host" class="panel" hidden><h2>Host controls</h2><p>Keep this host link private. Use the projector link on both TVs.</p><div id="links"></div>
<details><summary>Team phone invitations</summary><p>Share each invitation only with that team’s leaders. Multiple phones can use the same team link.</p><div id="teamLinks"></div></details>
<div class="controls"><label>Round length<select id="duration"><option value="10">10 seconds</option><option value="15" selected>15 seconds</option><option value="30">30 seconds</option><option value="60">60 seconds</option></select></label><button id="arm">Start buzzer round</button><button id="closeBuzz" class="secondary">Close buzzer</button></div>
<p class="muted">Three-second countdown, then buzz. Close the round to finalize the order; award +1 to a correct answer or the speed-round winner. Use score −/+ to correct a ruling.</p>
<hr><h3>Majority Rules</h3><p id="surveyStatus"></p><div class="controls"><button id="closeSurvey" class="secondary">Close arrival survey</button><label>Question<select id="questionSelect"></select></label><button id="showQuestion">Open team predictions</button><button id="reveal" class="secondary">Reveal & score</button></div><p class="muted">First prediction from either phone locks the team’s answer. Matching the majority earns +1. On a tie, every team that submitted gets +1. Revealing again never scores twice.</p></section>
<section id="survey" class="panel" hidden><h2>Your answers. Your opinion.</h2><p>Choose A or B for all ten. Your answers stay hidden until the host reveals each result.</p><form id="ballot"><div id="surveyQuestions"></div><button type="submit">Lock in my answers</button></form><div id="thanks" hidden><h2>You’re in!</h2><p>Your answers are locked. Let the guessing begin.</p><button id="nextStudent" class="secondary" hidden>Next student on this shared device</button></div></section>
<section id="playArea"><div class="arena panel"><p class="eyebrow" id="roundLabel">WAITING FOR THE HOST</p><h2 id="headline">Get your team ready.</h2><p id="roundStatus" role="status"></p><div id="questionOptions"></div><div id="predictionButtons" hidden><button data-answer="a">Predict A</button><button data-answer="b">Predict B</button></div><div id="resultBars"></div><button id="buzz" hidden disabled>BUZZ!</button><p id="timing" class="muted"></p></div>
<div class="columns"><section class="panel"><h2>Buzz order</h2><ol id="ranking"></ol><p id="emptyRanking" class="muted">The first phone from each team counts.</p><button id="sound" class="secondary">Enable chime</button></section><section class="panel"><h2>Scoreboard</h2><div id="scores"></div></section></div></section>
</section><footer>Game Buzzer · v1.0.0 · Fast fingers, friendly competition.</footer></main><script src="app.js" defer></script></body></html>
