<?php
declare(strict_types=1);
require_once __DIR__ . '/lib.php';
if (!user()) { header('Location: login.php'); exit; }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#13251f"><title><?=e(APP_NAME)?></title><link rel="stylesheet" href="assets/app.css"></head><body><header class="topbar"><a class="brand" href="#dashboard"><span class="brand-mark small">LG</span><span><strong>Life Group</strong><small>Attendance Portal</small></span></a><nav id="nav"><button data-view="dashboard" class="active">Dashboard</button><button data-view="checkin">Check-in</button><button data-view="students">Students</button><button data-view="reports">Reports</button></nav><div class="user-menu"><span><?=e(user()['name'])?></span><a href="logout.php">Sign out</a></div></header>
<main class="shell">
 <section id="view-dashboard" class="view active"><div class="page-head"><div><p class="eyebrow">OVERVIEW</p><h1>Good to see you, <?=e(explode(' ', user()['name'])[0])?>.</h1><p>Here’s what’s happening across your life groups.</p></div><button class="button primary" data-go="checkin">Take attendance</button></div><div id="stats" class="stat-grid"></div><div class="grid two"><article class="panel"><div class="panel-head"><div><p class="eyebrow">RECENT ACTIVITY</p><h2>Attendance trend</h2></div><select id="trendGroup" aria-label="Filter attendance trend"></select></div><div id="trendChart" class="chart"></div></article><article class="panel"><div class="panel-head"><div><p class="eyebrow">GROUPS</p><h2>Life groups</h2></div><button class="button subtle" id="newGroup">+ New group</button></div><div id="groupList" class="list"></div></article></div></section>
 <section id="view-checkin" class="view"><div class="page-head"><div><p class="eyebrow">QUICK CHECK-IN</p><h1>Who’s here tonight?</h1><p>Search by first or last name, then tap to mark present.</p></div><div class="date-pill" id="todayLabel"></div></div><article class="panel"><div class="filters"><select id="checkinGroup"><option value="">Choose a life group</option></select><select id="genderFilter"><option value="">All genders</option><option>Female</option><option>Male</option><option>Other</option></select><select id="gradeFilter"><option value="">All grades</option></select></div><div class="search-wrap"><span>⌕</span><input id="checkinSearch" placeholder="Start typing a student’s name…" autocomplete="off"><button class="button primary" id="quickAdd">+ New student</button></div><div id="checkinMeta" class="result-meta"></div><div id="checkinResults" class="student-results empty-state">Choose a group to begin.</div><div class="checkin-footer"><span id="presentCount">0 present</span><button class="button primary" id="saveAttendance">Save attendance</button></div></article></section>
 <section id="view-students" class="view"><div class="page-head"><div><p class="eyebrow">DIRECTORY</p><h1>Students</h1><p>Profiles, family connections, serving, baptism, and attendance history.</p></div><div class="filters"><button class="button" id="importFrontlines">Import Frontlines roster</button><button class="button primary" id="addStudent">+ Add student</button></div></div><article class="panel"><div class="filters"><input id="studentSearch" placeholder="Search first or last name"><select id="studentGroup"><option value="">All groups</option></select><select id="studentGrade"><option value="">All grades</option></select><select id="studentGender"><option value="">All genders</option><option>Female</option><option>Male</option><option>Other</option></select></div><div id="studentTable"></div></article></section>
 <section id="view-reports" class="view"><div class="page-head"><div><p class="eyebrow">INSIGHTS</p><h1>Attendance reports</h1><p>See totals over time across the ministry, per group, and per student.</p></div></div><div class="grid three"><article class="panel report-card"><p>Total check-ins</p><strong id="totalCheckins">0</strong><small>All recorded attendance</small></article><article class="panel report-card"><p>Average attendance</p><strong id="avgAttendance">0</strong><small>Per gathering</small></article><article class="panel report-card"><p>Students tracked</p><strong id="trackedStudents">0</strong><small>Active profiles</small></article></div><article class="panel"><div class="panel-head"><div><p class="eyebrow">BY GROUP</p><h2>Group attendance</h2></div></div><div id="reportGroups"></div></article></section>
</main><dialog id="modal"><form method="dialog" class="modal-card"><button class="icon-button close" value="cancel" aria-label="Close">×</button><div id="modalContent"></div></form></dialog><div id="toast" role="status"></div><script>window.APP={csrf:<?=json_encode(csrf())?>,user:<?=json_encode(user())?>};</script><script src="assets/app.js"></script></body></html>
