/* GPS ETA Drive Mode - Rev 1.8.14 */
(function(){
var STORE='gpsEtaDriveModeV1',MAP_STORE='gpsEtaLargeMapV1';
function id(x){return document.getElementById(x);}function text(src){var e=id(src);return e&&e.textContent?e.textContent.trim():'--';}function set(dst,val){var e=id(dst);if(e)e.textContent=val||'--';}
function makeStyle(){if(id('gpsDriveModeStyle'))return;var css='html,body{background:#101114!important;min-height:100dvh}body{padding-bottom:240px!important}.gps-drive-bar{position:fixed;left:0;right:0;bottom:0;z-index:9999;background:rgba(15,23,42,.96);border-top:1px solid rgba(255,255,255,.18);backdrop-filter:blur(8px);padding:8px 10px calc(8px + env(safe-area-inset-bottom));box-shadow:0 -8px 28px rgba(0,0,0,.35)}.gps-drive-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;align-items:center}.gps-drive-item{min-width:0;text-align:center}.gps-drive-label{font-size:.68rem;color:#93a4bd;text-transform:uppercase;letter-spacing:.05em}.gps-drive-value{font-weight:800;font-size:clamp(.95rem,4vw,1.25rem);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.gps-drive-actions{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:6px}.gps-drive-actions button{padding:8px 6px;margin:0;font-size:.8rem}.gps-toolbar-active{background:#22c55e!important;color:#06130a!important;border:2px solid #bbf7d0!important;box-shadow:0 0 0 3px rgba(34,197,94,.25)!important;font-weight:900}.gps-toolbar-inactive{background:rgba(229,231,235,.88)!important;color:#111827!important;opacity:.78}.gps-drive-late{color:#f87171}.gps-drive-ahead{color:#4ade80}.gps-drive-on section.card{margin-bottom:10px}.gps-map-full #liveMap{height:70vh!important}.gps-map-full #liveMapCard{position:relative;z-index:50}@media(max-width:520px){.gps-drive-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.gps-drive-item:nth-child(4),.gps-drive-item:nth-child(5){grid-column:span 1}.gps-drive-actions{grid-template-columns:repeat(2,1fr)}}';var s=document.createElement('style');s.id='gpsDriveModeStyle';s.textContent=css;document.head.appendChild(s);}
function item(label,idv){var d=document.createElement('div');d.className='gps-drive-item';var l=document.createElement('div');l.className='gps-drive-label';l.textContent=label;var v=document.createElement('div');v.className='gps-drive-value';v.id=idv;v.textContent='--';d.appendChild(l);d.appendChild(v);return d;}
function btn(label,fn,idv){var b=document.createElement('button');b.type='button';b.className='secondary';if(idv)b.id=idv;b.textContent=label;b.addEventListener('click',fn);return b;}
function make(){if(id('gpsDriveBar'))return;makeStyle();var bar=document.createElement('div');bar.id='gpsDriveBar';bar.className='gps-drive-bar';var grid=document.createElement('div');grid.className='gps-drive-grid';grid.appendChild(item('Speed','driveSpeed'));grid.appendChild(item('Remaining','driveRemaining'));grid.appendChild(item('ETA','driveEta'));grid.appendChild(item('Adjusted','driveAdjustedEta'));grid.appendChild(item('GPS','driveGps'));bar.appendChild(grid);var actions=document.createElement('div');actions.className='gps-drive-actions';actions.appendChild(btn('Drive Mode Off',toggleDrive,'driveModeToolbarBtn'));actions.appendChild(btn('Recenter Map',function(){if(window.gpsEtaLiveMap)window.gpsEtaLiveMap.recenter();},'recenterMapToolbarBtn'));actions.appendChild(btn('Map Normal',toggleMap,'mapSizeToolbarBtn'));actions.appendChild(btn('Clear Trail',function(){if(window.gpsEtaLiveMap)window.gpsEtaLiveMap.clearTrail();},'clearTrailToolbarBtn'));bar.appendChild(actions);document.body.appendChild(bar);if(localStorage.getItem(STORE)==='1'){document.body.classList.add('gps-drive-on');hideLowPriority(true);}if(localStorage.getItem(MAP_STORE)==='1')document.body.classList.add('gps-map-full');syncToolbar();}
function toolbarState(button,on,onText,offText){if(!button)return;button.textContent=on?'✓ '+onText:offText;button.setAttribute('aria-pressed',on?'true':'false');button.classList.toggle('gps-toolbar-active',on);button.classList.toggle('gps-toolbar-inactive',!on);}
function syncToolbar(){toolbarState(id('driveModeToolbarBtn'),document.body.classList.contains('gps-drive-on'),'Drive Mode On','Drive Mode Off');toolbarState(id('mapSizeToolbarBtn'),document.body.classList.contains('gps-map-full'),'Large Map On','Map Normal');}
function toggleDrive(){var on=!document.body.classList.contains('gps-drive-on');document.body.classList.toggle('gps-drive-on',on);localStorage.setItem(STORE,on?'1':'0');hideLowPriority(on);syncToolbar();}
function hideLowPriority(on){var cards=document.querySelectorAll('section.card,.card');cards.forEach(function(c){var t=(c.textContent||'').slice(0,160).toLowerCase();var low=t.indexOf('changelog')>=0||t.indexOf('device history')>=0||t.indexOf('trip log')>=0||t.indexOf('php stored trips')>=0||t.indexOf('no-api trip tools')>=0;if(low){c.style.display=on?'none':'';}});}
function toggleMap(){var on=!document.body.classList.contains('gps-map-full');document.body.classList.toggle('gps-map-full',on);localStorage.setItem(MAP_STORE,on?'1':'0');syncToolbar();setTimeout(function(){if(window.gpsEtaLiveMap)window.gpsEtaLiveMap.invalidate();},250);}
function alertText(){var a=text('adjEtaValue'),c=text('adjCurrentEta');if(a==='--'||c==='--')return'--';var d=text('etaDriftValue');return d==='--'?a:a+' '+d;}
function sync(){set('driveSpeed',text('speedValue')+' '+text('speedUnit'));set('driveRemaining',text('remainingValue')+' '+text('remainingUnit'));set('driveEta',text('arrivalTime'));set('driveAdjustedEta',alertText());set('driveGps',text('gpsQualityValue'));var dv=id('driveAdjustedEta');if(dv){var t=dv.textContent||'';dv.classList.toggle('gps-drive-late',t.indexOf('later')>=0);dv.classList.toggle('gps-drive-ahead',t.indexOf('earlier')>=0);}syncToolbar();}
make();setInterval(function(){sync();if(document.body.classList.contains('gps-drive-on'))hideLowPriority(true);},700);
})();
