/* GPS ETA Drift Indicator - Rev 1.8.3 */
(function(){
var KEY='gpsEtaBaselineEtaV1';
function n(v){var x=Number(v);return Number.isFinite(x)?x:null;}
function make(){if(document.getElementById('etaDriftCard'))return;var grid=document.querySelector('section.grid');if(!grid)return;var card=document.createElement('div');card.className='metric full';card.id='etaDriftCard';card.innerHTML='<div class="metric-title">ETA Drift vs Original Estimate</div><div id="etaDriftValue" class="metric-value" style="font-size:clamp(1.45rem,6vw,2.6rem)">--</div><div id="etaDriftDetail" class="metric-unit">Locks after the first valid ETA in this trip</div><div style="position:relative;height:18px;border-radius:999px;margin-top:12px;background:linear-gradient(90deg,#ef4444 0%,#f59e0b 45%,#eab308 50%,#22c55e 100%);border:1px solid rgba(255,255,255,.18);overflow:hidden"><div style="position:absolute;left:50%;top:0;bottom:0;width:2px;background:rgba(0,0,0,.55)"></div><div id="etaDriftPointer" style="position:absolute;left:50%;top:-4px;width:10px;height:26px;border-radius:999px;background:#fff;box-shadow:0 0 10px rgba(0,0,0,.65);transform:translateX(-50%)"></div></div><div id="etaDriftScale" class="metric-unit" style="display:flex;justify-content:space-between;margin-top:6px"><span>later</span><span>original</span><span>earlier</span></div>';var eta=document.getElementById('etaDuration');var ref=eta?eta.closest('.metric'):null;if(ref&&ref.parentNode)ref.parentNode.insertBefore(card,ref.nextSibling);else grid.appendChild(card);}
function readBase(){try{return JSON.parse(localStorage.getItem(KEY)||'null');}catch(e){return null;}}
function saveBase(b){localStorage.setItem(KEY,JSON.stringify(b));}
function clearBase(){localStorage.removeItem(KEY);}
function fmtClock(ms){return new Date(ms).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}
function fmtDelta(min){var abs=Math.abs(min);if(abs<0.5)return'On original ETA';var rounded=Math.round(abs);return rounded+' min '+(min>0?'later':'earlier');}
function set(id,text){var el=document.getElementById(id);if(el)el.textContent=text;}
function update(){if(typeof tripActive==='undefined'||!tripActive){clearBase();set('etaDriftValue','--');set('etaDriftDetail','Start tracking to lock original ETA');var p=document.getElementById('etaDriftPointer');if(p)p.style.left='50%';return;}var speed=typeof avgCurrentSpeed==='function'?avgCurrentSpeed():0;var rem=typeof remainingMeters==='function'?remainingMeters():0;if(!Number.isFinite(speed)||speed<0.4||!Number.isFinite(rem)||rem<=0){set('etaDriftValue','--');set('etaDriftDetail','Waiting for a valid speed and remaining distance');return;}var currentArrival=Date.now()+(rem/speed*1000);var base=readBase();var startMeters=typeof tripStartMeters!=='undefined'?tripStartMeters:null;if(!base||base.startMeters!==startMeters){base={startMeters:startMeters,createdAt:Date.now(),baselineArrival:currentArrival,unit:typeof label==='function'?label():'miles'};saveBase(base);}var deltaMin=(currentArrival-base.baselineArrival)/60000;var pointer=50-(Math.max(-30,Math.min(30,deltaMin))/30*50);var p=document.getElementById('etaDriftPointer');if(p)p.style.left=pointer+'%';set('etaDriftValue',fmtDelta(deltaMin));set('etaDriftDetail','Original '+fmtClock(base.baselineArrival)+' | Current '+fmtClock(currentArrival)+' | Offset '+(deltaMin>=0?'+':'')+deltaMin.toFixed(1)+' min');}
make();setInterval(update,1000);update();
})();
