/* GPS ETA Quality Indicator - Rev 1.8.2 */
(function(){
var last=null,interval=null;
function m(v){var n=Number(v);return Number.isFinite(n)?n:null;}
function quality(acc,age){if(age>15)return['Stale','No recent update'];if(acc===null)return['Unknown','No accuracy'];if(acc<=5)return['Excellent','tight fix'];if(acc<=10)return['Good','strong fix'];if(acc<=30)return['Usable','acceptable'];if(acc<=100)return['Weak','reduced'];return['Poor','low confidence'];}
function setText(id,value){var el=document.getElementById(id);if(el)el.textContent=value;}
function hideOldAccuracy(){var acc=document.getElementById('accuracyValue');var card=acc?acc.closest('.metric'):null;if(card)card.style.display='none';}
function make(){if(document.getElementById('gpsSignalCard'))return;var grid=document.querySelector('section.grid');if(!grid)return;hideOldAccuracy();var card=document.createElement('div');card.className='metric full';card.id='gpsSignalCard';card.innerHTML='<div class="metric-title">GPS Signal</div><div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;align-items:start"><div><div id="gpsSignalAccuracy" class="metric-value" style="font-size:clamp(1.25rem,5vw,2.1rem)">--</div><div class="metric-unit">accuracy</div></div><div><div id="gpsQualityValue" class="metric-value" style="font-size:clamp(1.25rem,5vw,2.1rem)">--</div><div id="gpsQualityDetail" class="metric-unit">quality</div></div><div><div id="gpsAgeValue" class="metric-value" style="font-size:clamp(1.25rem,5vw,2.1rem)">--</div><div id="gpsSourceValue" class="metric-unit">update age</div></div></div>';var loc=document.getElementById('locationValue');var ref=loc?loc.closest('.metric'):null;if(ref&&ref.parentNode)ref.parentNode.insertBefore(card,ref);else grid.appendChild(card);}
function tick(){if(!last){setText('gpsSignalAccuracy','--');setText('gpsQualityValue','--');setText('gpsAgeValue','--');return;}var age=(Date.now()-last.receivedAt)/1000;var q=quality(last.accuracy,age);setText('gpsSignalAccuracy',last.accuracy!==null?Math.round(last.accuracy*3.28084)+' ft':'--');setText('gpsQualityValue',q[0]);setText('gpsQualityDetail',q[1]);setText('gpsAgeValue',age<60?age.toFixed(1)+'s':Math.round(age)+'s');setText('gpsSourceValue','S: '+(last.hasSpeed?'native':'calc')+' | H: '+(last.hasHeading?'native':'move'));}
function hook(){if(!navigator.geolocation||navigator.geolocation._gpsEtaQualityHooked)return;var original=navigator.geolocation.watchPosition.bind(navigator.geolocation);navigator.geolocation.watchPosition=function(success,error,options){return original(function(pos){last={receivedAt:Date.now(),accuracy:m(pos.coords.accuracy),hasSpeed:m(pos.coords.speed)!==null,hasHeading:m(pos.coords.heading)!==null};tick();success(pos);},error,options);};navigator.geolocation._gpsEtaQualityHooked=true;}
make();hook();interval=setInterval(tick,1000);
})();
