/* GPS ETA Quality Indicator - Rev 1.7.0 */
(function(){
var last=null,interval=null;
function m(v){var n=Number(v);return Number.isFinite(n)?n:null;}
function quality(acc,age){if(age>15)return['Stale','No recent GPS update'];if(acc===null)return['Unknown','No accuracy value'];if(acc<=5)return['Excellent','Very tight location fix'];if(acc<=10)return['Good','Strong location fix'];if(acc<=30)return['Usable','Acceptable for driving'];if(acc<=100)return['Weak','Reduced confidence'];return['Poor','Low confidence'];}
function make(){if(document.getElementById('gpsQualityValue'))return;var grid=document.querySelector('section.grid');if(!grid)return;var card=document.createElement('div');card.className='metric';card.innerHTML='<div class="metric-title">GPS Quality</div><div id="gpsQualityValue" class="metric-value">--</div><div id="gpsQualityDetail" class="metric-unit">Waiting for GPS update</div>';var acc=document.getElementById('accuracyValue');var ref=acc?acc.closest('.metric'):null;if(ref&&ref.parentNode)ref.parentNode.insertBefore(card,ref.nextSibling);else grid.appendChild(card);var age=document.createElement('div');age.className='metric';age.innerHTML='<div class="metric-title">GPS Update Age</div><div id="gpsAgeValue" class="metric-value">--</div><div id="gpsSourceValue" class="metric-unit">Speed/heading source unknown</div>';if(card.parentNode)card.parentNode.insertBefore(age,card.nextSibling);else grid.appendChild(age);}
function setText(id,value){var el=document.getElementById(id);if(el)el.textContent=value;}
function tick(){if(!last){setText('gpsQualityValue','--');setText('gpsAgeValue','--');return;}var age=(Date.now()-last.receivedAt)/1000;var q=quality(last.accuracy,age);setText('gpsQualityValue',q[0]);setText('gpsQualityDetail',(last.accuracy!==null?Math.round(last.accuracy*3.28084)+' ft accuracy. ':'')+q[1]);setText('gpsAgeValue',age<60?age.toFixed(1)+'s':Math.round(age)+'s');setText('gpsSourceValue','Speed: '+(last.hasSpeed?'native GPS':'calculated')+' | Heading: '+(last.hasHeading?'native GPS':'movement'));}
function hook(){if(!navigator.geolocation||navigator.geolocation._gpsEtaQualityHooked)return;var original=navigator.geolocation.watchPosition.bind(navigator.geolocation);navigator.geolocation.watchPosition=function(success,error,options){return original(function(pos){last={receivedAt:Date.now(),accuracy:m(pos.coords.accuracy),hasSpeed:m(pos.coords.speed)!==null,hasHeading:m(pos.coords.heading)!==null};tick();success(pos);},error,options);};navigator.geolocation._gpsEtaQualityHooked=true;}
make();hook();interval=setInterval(tick,1000);
})();
