/* GPS ETA Live Map - Rev 1.8.5 */
(function(){
var map=null,marker=null,circle=null,path=null,points=[],last=null,lastDraw=0,follow=true;
function n(v){var x=Number(v);return Number.isFinite(x)?x:null;}
function set(id,value){var el=document.getElementById(id);if(el)el.textContent=value;}
function makeCard(){if(document.getElementById('liveMapCard'))return;var grid=document.querySelector('section.grid');if(!grid)return;var card=document.createElement('div');card.className='metric full';card.id='liveMapCard';var title=document.createElement('div');title.className='metric-title';title.textContent='Live Map';card.appendChild(title);var box=document.createElement('div');box.id='liveMap';box.style.height='260px';box.style.borderRadius='14px';box.style.overflow='hidden';box.style.border='1px solid var(--border)';box.style.marginTop='10px';card.appendChild(box);var info=document.createElement('div');info.className='metric-unit';info.id='liveMapInfo';info.textContent='Waiting for GPS location.';info.style.marginTop='8px';card.appendChild(info);var raw=document.getElementById('rawGpsValue');var ref=raw?raw.closest('.metric'):null;if(ref&&ref.parentNode)ref.parentNode.insertBefore(card,ref);else grid.appendChild(card);}
function init(lat,lon){if(map||typeof L==='undefined')return;map=L.map('liveMap').setView([lat,lon],16);var url='https://tile.openstreetmap.org/{z}/{x}/{y}.png';L.tileLayer(url,{maxZoom:19}).addTo(map);marker=L.marker([lat,lon]).addTo(map);circle=L.circle([lat,lon],{radius:25}).addTo(map);path=L.polyline([]).addTo(map);setTimeout(function(){map.invalidateSize();},300);}
function draw(force){if(!last)return;var now=Date.now();if(!force&&now-lastDraw<10000)return;lastDraw=now;init(last.lat,last.lon);if(!map)return;var p=[last.lat,last.lon];points.push(p);if(points.length>250)points.shift();marker.setLatLng(p);circle.setLatLng(p);if(last.acc!==null)circle.setRadius(last.acc);path.setLatLngs(points);if(follow)map.setView(p,map.getZoom()||16);set('liveMapInfo','Current: '+last.lat.toFixed(6)+', '+last.lon.toFixed(6)+' | Accuracy: '+(last.acc!==null?Math.round(last.acc*3.28084)+' ft':'--')+' | Updated: '+new Date(now).toLocaleTimeString());}
function hook(){if(!navigator.geolocation||navigator.geolocation._gpsEtaLiveMap)return;var original=navigator.geolocation.watchPosition.bind(navigator.geolocation);navigator.geolocation.watchPosition=function(success,error,options){return original(function(pos){var lat=n(pos.coords.latitude),lon=n(pos.coords.longitude);if(lat!==null&&lon!==null){last={lat:lat,lon:lon,acc:n(pos.coords.accuracy)};draw(false);}success(pos);},error,options);};navigator.geolocation._gpsEtaLiveMap=true;}
makeCard();hook();setInterval(function(){draw(false);},1000);window.addEventListener('focus',function(){setTimeout(function(){if(map)map.invalidateSize();draw(true);},300);});
})();
