<?php
/* GPS ETA PHP Trip Store - Rev 1.8.0 */
const DIR = __DIR__ . '/data/trip-sessions';
const DAYS = 365;
const MAX_BODY = 65536;
function send_json($data, $code = 200) { http_response_code($code); header('Content-Type: application/json; charset=utf-8'); header('X-Content-Type-Options: nosniff'); echo json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES); exit; }
function req_json() { $raw = file_get_contents('php://input', false, null, 0, MAX_BODY + 1); if ($raw === false || trim($raw) === '') return []; if (strlen($raw) > MAX_BODY) send_json(['ok'=>false,'error'=>'Request too large'],413); $data = json_decode($raw, true); return is_array($data) ? $data : []; }
function clean_id($value) { $value = preg_replace('/[^A-Za-z0-9_.:-]/', '', trim((string)$value)) ?? ''; return substr($value, 0, 120); }
function must_id($value, $name) { $id = clean_id($value); if ($id === '') send_json(['ok'=>false,'error'=>'Missing '.$name],400); return $id; }
function ensure_dir() { if (!is_dir(DIR) && !mkdir(DIR, 0755, true) && !is_dir(DIR)) send_json(['ok'=>false,'error'=>'Storage unavailable'],500); }
function store_path($device) { ensure_dir(); return DIR . '/' . hash('sha256', $device) . '.json'; }
function num_val($value, $min = null, $max = null) { if (!is_numeric($value)) return null; $n = $value + 0; if ($min !== null && $n < $min) return null; if ($max !== null && $n > $max) return null; return $n; }
function str_val($value, $max = 160) { if (is_array($value) || is_object($value)) $value = json_encode($value); return substr((string)$value, 0, $max); }
function load_store($device) { $path = store_path($device); if (!is_readable($path)) return ['schema'=>'gps-eta-trip-store-v1','deviceHash'=>hash('sha256',$device),'createdAt'=>gmdate('c'),'updatedAt'=>gmdate('c'),'trips'=>[]]; $data = json_decode((string)file_get_contents($path), true); if (!is_array($data)) $data = []; $data['schema'] = $data['schema'] ?? 'gps-eta-trip-store-v1'; $data['deviceHash'] = $data['deviceHash'] ?? hash('sha256',$device); $data['createdAt'] = $data['createdAt'] ?? gmdate('c'); $data['updatedAt'] = $data['updatedAt'] ?? gmdate('c'); $data['trips'] = isset($data['trips']) && is_array($data['trips']) ? $data['trips'] : []; return $data; }
function trip_time($trip) { $stamp = $trip['endAt'] ?? $trip['lastAt'] ?? $trip['startAt'] ?? null; $t = is_string($stamp) ? strtotime($stamp) : false; return $t === false ? 0 : $t; }
function prune_store($store) { $cut = time() - (DAYS * 86400); $kept = []; foreach (($store['trips'] ?? []) as $id => $trip) { if (!is_array($trip)) continue; if (trip_time($trip) >= $cut) $kept[$id] = $trip; } $store['trips'] = $kept; return $store; }
function save_store($device, $store) { $store = prune_store($store); $store['updatedAt'] = gmdate('c'); $json = json_encode($store, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES); if ($json === false || file_put_contents(store_path($device), $json, LOCK_EX) === false) send_json(['ok'=>false,'error'=>'Save failed'],500); }
function clean_entry($entry) { $iso = str_val($entry['iso'] ?? gmdate('c'), 40); if (strtotime($iso) === false) $iso = gmdate('c'); return ['id'=>bin2hex(random_bytes(8)),'savedAt'=>gmdate('c'),'iso'=>$iso,'reason'=>str_val($entry['reason'] ?? '',40),'elapsed'=>str_val($entry['elapsed'] ?? '',40),'elapsedSeconds'=>num_val($entry['elapsedSeconds'] ?? null,0,315360000),'tracked'=>num_val($entry['tracked'] ?? null,0,1000000),'remaining'=>num_val($entry['remaining'] ?? null,0,1000000),'unit'=>in_array(($entry['unit'] ?? 'miles'),['miles','km'],true)?$entry['unit']:'miles','speed'=>num_val($entry['speed'] ?? null,0,10000),'speedUnit'=>in_array(($entry['speedUnit'] ?? 'mph'),['mph','km/h'],true)?$entry['speedUnit']:'mph','heading'=>str_val($entry['heading'] ?? '',40),'accuracy'=>str_val($entry['accuracy'] ?? '',60),'latlon'=>str_val($entry['latlon'] ?? '',80)]; }
function clean_summary($summary) { return ['endedAt'=>gmdate('c'),'startDistance'=>num_val($summary['startDistance'] ?? null,0,1000000),'tracked'=>num_val($summary['tracked'] ?? null,0,1000000),'remaining'=>num_val($summary['remaining'] ?? null,0,1000000),'unit'=>in_array(($summary['unit'] ?? 'miles'),['miles','km'],true)?$summary['unit']:'miles','elapsedSeconds'=>num_val($summary['elapsedSeconds'] ?? null,0,315360000),'movingSeconds'=>num_val($summary['movingSeconds'] ?? null,0,315360000),'stoppedSeconds'=>num_val($summary['stoppedSeconds'] ?? null,0,315360000),'avgSpeed'=>num_val($summary['avgSpeed'] ?? null,0,10000),'avgMovingSpeed'=>num_val($summary['avgMovingSpeed'] ?? null,0,10000),'maxSpeed'=>num_val($summary['maxSpeed'] ?? null,0,10000),'speedUnit'=>in_array(($summary['speedUnit'] ?? 'mph'),['mph','km/h'],true)?$summary['speedUnit']:'mph','startLocation'=>str_val($summary['startLocation'] ?? '',80),'endLocation'=>str_val($summary['endLocation'] ?? '',80),'snapshotCount'=>num_val($summary['snapshotCount'] ?? null,0,100000)]; }
$action = $_GET['action'] ?? '';
$body = req_json();
$device = must_id($_GET['deviceId'] ?? ($body['deviceId'] ?? ''), 'device ID');
if ($action === 'list') { $store = prune_store(load_store($device)); save_store($device, $store); $trips = array_values($store['trips']); usort($trips, fn($a,$b)=>trip_time($b)<=>trip_time($a)); send_json(['ok'=>true,'schema'=>$store['schema'],'retentionDays'=>DAYS,'count'=>count($trips),'trips'=>array_slice($trips,0,100)]); }
if ($action === 'log') { if ($_SERVER['REQUEST_METHOD'] !== 'POST') send_json(['ok'=>false,'error'=>'POST required'],405); $tripId = must_id($body['tripId'] ?? '', 'trip ID'); $entry = $body['entry'] ?? null; if (!is_array($entry)) send_json(['ok'=>false,'error'=>'Missing entry'],400); $store = prune_store(load_store($device)); if (!isset($store['trips'][$tripId])) $store['trips'][$tripId] = ['tripId'=>$tripId,'status'=>'active','startAt'=>gmdate('c'),'lastAt'=>gmdate('c'),'entries'=>[],'summary'=>null]; $clean = clean_entry($entry); $store['trips'][$tripId]['lastAt'] = $clean['iso']; $store['trips'][$tripId]['entries'][] = $clean; save_store($device,$store); send_json(['ok'=>true,'tripId'=>$tripId,'entryCount'=>count($store['trips'][$tripId]['entries'])]); }
if ($action === 'end') { if ($_SERVER['REQUEST_METHOD'] !== 'POST') send_json(['ok'=>false,'error'=>'POST required'],405); $tripId = must_id($body['tripId'] ?? '', 'trip ID'); $summary = $body['summary'] ?? null; if (!is_array($summary)) send_json(['ok'=>false,'error'=>'Missing summary'],400); $store = prune_store(load_store($device)); if (!isset($store['trips'][$tripId])) $store['trips'][$tripId] = ['tripId'=>$tripId,'startAt'=>gmdate('c'),'entries'=>[]]; $store['trips'][$tripId]['status'] = 'ended'; $store['trips'][$tripId]['endAt'] = gmdate('c'); $store['trips'][$tripId]['lastAt'] = gmdate('c'); $store['trips'][$tripId]['summary'] = clean_summary($summary); save_store($device,$store); send_json(['ok'=>true,'tripId'=>$tripId,'summary'=>$store['trips'][$tripId]['summary']]); }
if ($action === 'delete') { if ($_SERVER['REQUEST_METHOD'] !== 'POST') send_json(['ok'=>false,'error'=>'POST required'],405); $path = store_path($device); $deleted = is_file($path) ? unlink($path) : false; send_json(['ok'=>true,'deleted'=>$deleted]); }
send_json(['ok'=>false,'error'=>'Unknown action'],404);
