<?php require __DIR__ . '/lib.php'; $logged = admin_logged_in(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quiz Web Interactive Admin</title><link rel="stylesheet" href="assets/app.css"></head><body><main class="shell"><div class="topbar"><h1>Quiz Web Interactive</h1><a class="button secondary" href="index.php">Player home</a></div>
<section id="loginCard" class="card <?=$logged?'hidden':''?>"><h2>Admin sign in</h2><form id="login"><label>Password<input type="password" name="password" required></label><br><button>Sign in</button></form><p id="loginError" class="status wrong hidden"></p></section>
<div id="adminArea" class="<?=$logged?'':'hidden'?>"><section class="card"><div class="topbar"><h2>Quiz library</h2><button id="newQuiz" class="secondary">New quiz</button></div><div id="quizList"></div></section>
<section class="card hidden" id="builder"><h2>Create quiz</h2><form id="quizForm"><input type="hidden" name="quiz_id"><label>Quiz title<input name="title" required placeholder="Friday Team Trivia"></label><div id="questions"></div><div class="row"><button type="button" class="secondary" id="addQuestion">Add question</button><button type="submit">Save quiz</button></div></form><p id="buildError" class="status wrong hidden"></p></section>
<section class="card hidden" id="control"><div class="topbar"><div><h2 id="gameTitle">Game controls</h2><div class="code" id="gameCode"></div></div><div class="row"><a id="displayLink" class="button secondary" target="_blank">Open display</a><button id="logout" class="secondary">Log out</button></div></div><p id="phase" class="status"></p><div class="row"><button id="start">Start next question</button><button id="results" class="secondary">Show results now</button><button id="finish" class="danger">Finish game</button><button id="reset" class="secondary">Reset game</button></div><h3>Leaderboard</h3><div id="leaders"></div></section></div></main>
<script src="assets/app.js"></script><script>
let qCount=0,code=null,game=null;
function resetBuilder(){qCount=0;document.getElementById('questions').innerHTML='';document.getElementById('quizForm').reset();addQuestion();document.getElementById('builder').classList.remove('hidden')}
function addQuestion(){qCount++;const wrap=document.createElement('div');wrap.className='question-editor';wrap.innerHTML=`<h3>Question ${qCount}</h3><label>Question<input data-field="text" required></label><p>Answers — select the correct one:</p>${[0,1,2,3].map(i=>`<div class="choice-row"><input type="radio" name="correct_${qCount}" value="${i}" ${i===0?'checked':''}><input data-choice="${i}" required placeholder="Answer ${i+1}"></div>`).join('')}<button type="button" class="secondary remove">Remove question</button>`;wrap.querySelector('.remove').onclick=()=>wrap.remove();document.getElementById('questions').appendChild(wrap)}
async function loadQuizzes(){const r=await api('list_quizzes');document.getElementById('quizList').innerHTML=r.quizzes.length?r.quizzes.map(q=>`<div class="leaderboard"><div class="row"><span><strong>${escapeHtml(q.title)}</strong> — ${q.question_count} questions</span><button onclick="launchQuiz('${q.id}')">Launch</button></div></div>`).join(''):'<p>No quizzes saved yet.</p>'}
async function launchQuiz(id){const r=await api('launch_quiz',{quiz_id:id});code=r.code;document.getElementById('control').classList.remove('hidden');document.getElementById('gameCode').textContent=code;document.getElementById('displayLink').href='display.php?code='+code;poll()}
document.getElementById('newQuiz').onclick=resetBuilder;document.getElementById('addQuestion').onclick=addQuestion;
document.getElementById('login').onsubmit=async e=>{e.preventDefault();try{await api('admin_login',Object.fromEntries(new FormData(e.target)));document.getElementById('loginCard').classList.add('hidden');document.getElementById('adminArea').classList.remove('hidden');loadQuizzes()}catch(err){const x=document.getElementById('loginError');x.textContent=err.message;x.classList.remove('hidden')}};
document.getElementById('quizForm').onsubmit=async e=>{e.preventDefault();const questions=[...document.querySelectorAll('.question-editor')].map(el=>({text:el.querySelector('[data-field="text"]').value,choices:[...el.querySelectorAll('[data-choice]')].map(x=>x.value),correct_index:+el.querySelector('input[type=radio]:checked').value}));try{await api('save_quiz',{title:e.target.title.value,questions});document.getElementById('builder').classList.add('hidden');await loadQuizzes()}catch(err){const x=document.getElementById('buildError');x.textContent=err.message;x.classList.remove('hidden')}};
async function poll(){if(!code)return;const r=await fetch(`api.php?action=state&code=${code}`,{cache:'no-store'});const j=await r.json();if(j.ok){game=j.game;document.getElementById('gameTitle').textContent=game.title;document.getElementById('phase').textContent=`Phase: ${game.phase} • Question ${game.question_number} of ${game.question_count} • ${game.players.length} teams`;document.getElementById('leaders').innerHTML=renderLeaderboard(game.players,game.players.length);document.getElementById('start').disabled=game.phase==='question'||game.question_number>=game.question_count;document.getElementById('results').disabled=game.phase!=='question';document.getElementById('finish').disabled=game.phase==='finished'}}
document.getElementById('start').onclick=async()=>{try{await api('start_question',{code});poll()}catch(e){alert(e.message)}};document.getElementById('results').onclick=async()=>{try{await api('show_results',{code});poll()}catch(e){alert(e.message)}};document.getElementById('finish').onclick=async()=>{try{await api('finish_game',{code});poll()}catch(e){alert(e.message)}};document.getElementById('reset').onclick=async()=>{if(!confirm(`Reset game ${code}? This removes all teams, scores, answers, and returns it to the lobby.`))return;try{await api('reset_game',{code});poll()}catch(e){alert(e.message)}};document.getElementById('logout').onclick=async()=>{await api('admin_logout');location.reload()};setInterval(poll,1000);if(<?= $logged?'true':'false' ?>)loadQuizzes();
</script></body></html>