<?php require __DIR__ . '/lib.php'; $logged = admin_logged_in(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quiz Web Interactive Admin</title><link rel="stylesheet" href="assets/app.css"></head><body><main class="shell"><div class="topbar"><h1>Quiz Web Interactive</h1><a class="button secondary" href="index.php">Player home</a></div>
<section id="loginCard" class="card <?=$logged?'hidden':''?>"><h2>Admin sign in</h2><form id="login"><label>Password<input type="password" name="password" required></label><br><button>Sign in</button></form><p id="loginError" class="status wrong hidden"></p></section>
<div id="adminArea" class="<?=$logged?'':'hidden'?>"><section class="card"><div class="topbar"><h2>Quiz library</h2><div class="row"><button id="showHistory" class="secondary">Game history</button><button id="showStats" class="secondary">Statistics</button><button id="newQuiz" class="secondary">New quiz</button></div></div><div id="quizList"></div></section>
<section class="card hidden" id="builder"><h2>Create quiz</h2><form id="quizForm"><input type="hidden" name="quiz_id"><label>Quiz title<input name="title" required placeholder="Friday Team Trivia"></label><div id="questions"></div><div class="row"><button type="button" class="secondary" id="addQuestion">Add new question</button><button type="button" class="secondary" id="openQuestionBank">Add from Question Bank</button><button type="submit">Save quiz</button></div></form><p id="buildError" class="status wrong hidden"></p></section>
<section class="card hidden" id="questionBank"><div class="topbar"><div><h2>Question Bank</h2><p class="muted">Search question text or any answer choice.</p></div><button type="button" class="secondary" id="closeQuestionBank">Close</button></div><label>Search questions or answers<input id="questionBankSearch" type="search" placeholder="Type a question or answer..."></label><div id="questionBankResults" class="question-bank-results"></div></section>
<section class="card hidden" id="historyPanel"><div class="topbar"><div><h2>Game history</h2><p class="muted">Search by quiz, team, invite code, or date.</p></div><button class="secondary" id="closeHistory">Close</button></div><label>Search history<input id="historySearch" type="search" placeholder="Team, quiz, code, or date..."></label><div id="historyResults"></div></section>
<section class="card hidden" id="statsPanel"><div class="topbar"><h2>Statistics</h2><button class="secondary" id="closeStats">Close</button></div><div id="statsResults"></div></section>
<section class="card hidden" id="control"><div class="topbar"><div><h2 id="gameTitle">Game controls</h2><div class="code" id="gameCode"></div></div><div class="row"><a id="displayLink" class="button secondary" target="_blank">Open display</a><button id="logout" class="secondary">Log out</button></div></div><p id="phase" class="status"></p><div class="row"><button id="start">Start next question</button><button id="results" class="secondary">Show results now</button><button id="finish" class="danger">Finish game</button><button id="reset" class="secondary">Archive and replay same code</button></div><h3>Leaderboard</h3><div id="leaders"></div></section></div></main>
<script src="assets/app.js"></script><script>
let qCount=0,code=null,game=null,bankSearchTimer=null,historySearchTimer=null;
function resetBuilder(){qCount=0;document.getElementById('questions').innerHTML='';document.getElementById('quizForm').reset();addQuestion();document.getElementById('builder').classList.remove('hidden')}
function addQuestion(question=null){qCount++;const wrap=document.createElement('div');wrap.className='question-editor';wrap.dataset.sourceQuestionId=question?.id||question?.source_question_id||'';const choices=question?.choices||['','','',''];const correct=Number.isInteger(question?.correct_index)?question.correct_index:0;wrap.innerHTML=`<h3>Question ${qCount}</h3><label>Question<input data-field="text" required value="${escapeHtml(question?.text||'')}"></label><p>Answers — select the correct one:</p>${[0,1,2,3].map(i=>`<div class="choice-row"><input type="radio" name="correct_${qCount}" value="${i}" ${i===correct?'checked':''}><input data-choice="${i}" required placeholder="Answer ${i+1}" value="${escapeHtml(choices[i]||'')}"></div>`).join('')}<label class="checkbox-row"><input type="checkbox" data-field="add_to_bank" ${question?'':'checked'}> <span>Add to Question Bank</span></label><button type="button" class="secondary remove">Remove question</button>`;wrap.querySelector('.remove').onclick=()=>wrap.remove();document.getElementById('questions').appendChild(wrap)}
async function loadQuizzes(){const r=await api('list_quizzes');document.getElementById('quizList').innerHTML=r.quizzes.length?r.quizzes.map(q=>`<div class="leaderboard"><div class="row"><span><strong>${escapeHtml(q.title)}</strong> — ${q.question_count} questions</span><button data-launch="${escapeHtml(q.id)}">Launch</button></div></div>`).join(''):'<p>No quizzes saved yet.</p>';document.querySelectorAll('[data-launch]').forEach(b=>b.onclick=()=>launchQuiz(b.dataset.launch))}
async function launchQuiz(id){const r=await api('launch_quiz',{quiz_id:id});code=r.code;document.getElementById('control').classList.remove('hidden');document.getElementById('gameCode').textContent=code;document.getElementById('displayLink').href='display.php?code='+code;poll()}
async function loadQuestionBank(search=''){const results=document.getElementById('questionBankResults');results.innerHTML='<p class="muted">Loading...</p>';try{const r=await api('list_question_bank',{search});results.innerHTML=r.questions.length?r.questions.map((q,index)=>`<article class="bank-question"><div><strong>${escapeHtml(q.text)}</strong><ol>${q.choices.map((a,i)=>`<li class="${i===q.correct_index?'bank-correct':''}">${escapeHtml(a)}${i===q.correct_index?' ✓':''}</li>`).join('')}</ol><p class="muted">Used ${q.times_used} time${q.times_used===1?'':'s'}</p></div><button data-bank-index="${index}">Add to quiz</button></article>`).join(''):'<p>No matching Question Bank entries.</p>';results.querySelectorAll('[data-bank-index]').forEach(b=>b.onclick=()=>addQuestion(r.questions[+b.dataset.bankIndex]))}catch(err){results.innerHTML=`<p class="status wrong">${escapeHtml(err.message)}</p>`}}
function formatDate(value){return value?new Date(value).toLocaleString():'—'}
async function loadHistory(search=''){const box=document.getElementById('historyResults');box.innerHTML='<p class="muted">Loading...</p>';try{const r=await api('list_game_history',{search});box.innerHTML=r.history.length?r.history.map(h=>`<article class="history-game"><div class="topbar"><div><strong>${escapeHtml(h.title)}</strong><div class="muted">Code ${escapeHtml(h.code)} • ${formatDate(h.finished_at)} • ${h.team_count} teams</div></div><span>${Math.round(h.duration_seconds/60)} min</span></div><ol class="leaderboard">${h.rankings.map(p=>`<li><span class="rank">${p.placement}</span><span><i class="swatch" style="background:${p.color}"></i>${escapeHtml(p.team_name)}</span><span class="points">${p.score.toLocaleString()}</span></li>`).join('')}</ol></article>`).join(''):'<p>No matching archived games.</p>'}catch(err){box.innerHTML=`<p class="status wrong">${escapeHtml(err.message)}</p>`}}
async function loadStats(){const box=document.getElementById('statsResults');box.innerHTML='<p class="muted">Loading...</p>';try{const r=await api('game_statistics'),s=r.statistics;box.innerHTML=`<div class="stats-grid"><div class="stat-card"><strong>${s.games_played}</strong><span>Games played</span></div><div class="stat-card"><strong>${s.average_score}</strong><span>Average score</span></div><div class="stat-card"><strong>${s.highest_score?s.highest_score.score:0}</strong><span>Highest score${s.highest_score?' — '+escapeHtml(s.highest_score.team_name):''}</span></div></div><h3>Team standings</h3>${s.teams.length?`<div class="table-wrap"><table><thead><tr><th>Team</th><th>Games</th><th>Wins</th><th>Avg score</th><th>Avg place</th></tr></thead><tbody>${s.teams.map(t=>`<tr><td>${escapeHtml(t.team_name)}</td><td>${t.games}</td><td>${t.wins}</td><td>${t.average_score}</td><td>${t.average_placement}</td></tr>`).join('')}</tbody></table></div>`:'<p>No team statistics yet.</p>'}<h3>Question performance</h3>${s.questions.length?`<div class="table-wrap"><table><thead><tr><th>Question</th><th>Used</th><th>Answers</th><th>Accuracy</th><th>Avg response</th></tr></thead><tbody>${s.questions.map(q=>`<tr><td>${escapeHtml(q.text)}</td><td>${q.times_used}</td><td>${q.answers}</td><td>${q.accuracy===null?'—':q.accuracy+'%'}</td><td>${q.average_response_time===null?'—':q.average_response_time+'s'}</td></tr>`).join('')}</tbody></table></div>`:'<p>No question statistics yet.</p>'}`}catch(err){box.innerHTML=`<p class="status wrong">${escapeHtml(err.message)}</p>`}}
document.getElementById('newQuiz').onclick=resetBuilder;document.getElementById('addQuestion').onclick=()=>addQuestion();document.getElementById('openQuestionBank').onclick=()=>{questionBank.classList.remove('hidden');loadQuestionBank(questionBankSearch.value)};document.getElementById('closeQuestionBank').onclick=()=>questionBank.classList.add('hidden');questionBankSearch.oninput=e=>{clearTimeout(bankSearchTimer);bankSearchTimer=setTimeout(()=>loadQuestionBank(e.target.value),250)};showHistory.onclick=()=>{historyPanel.classList.remove('hidden');loadHistory(historySearch.value)};closeHistory.onclick=()=>historyPanel.classList.add('hidden');historySearch.oninput=e=>{clearTimeout(historySearchTimer);historySearchTimer=setTimeout(()=>loadHistory(e.target.value),250)};showStats.onclick=()=>{statsPanel.classList.remove('hidden');loadStats()};closeStats.onclick=()=>statsPanel.classList.add('hidden');
document.getElementById('login').onsubmit=async e=>{e.preventDefault();try{await api('admin_login',Object.fromEntries(new FormData(e.target)));loginCard.classList.add('hidden');adminArea.classList.remove('hidden');loadQuizzes()}catch(err){loginError.textContent=err.message;loginError.classList.remove('hidden')}};
document.getElementById('quizForm').onsubmit=async e=>{e.preventDefault();const questions=[...document.querySelectorAll('.question-editor')].map(el=>({text:el.querySelector('[data-field="text"]').value,choices:[...el.querySelectorAll('[data-choice]')].map(x=>x.value),correct_index:+el.querySelector('input[type=radio]:checked').value,add_to_bank:el.querySelector('[data-field="add_to_bank"]').checked,source_question_id:el.dataset.sourceQuestionId||null}));try{await api('save_quiz',{title:e.target.title.value,questions});builder.classList.add('hidden');questionBank.classList.add('hidden');await loadQuizzes()}catch(err){buildError.textContent=err.message;buildError.classList.remove('hidden')}};
async function poll(){if(!code)return;const r=await fetch(`api.php?action=state&code=${code}`,{cache:'no-store'}),j=await r.json();if(j.ok){game=j.game;gameTitle.textContent=game.title;phase.textContent=`Phase: ${game.phase} • Question ${game.question_number} of ${game.question_count} • ${game.players.length} teams`;leaders.innerHTML=renderLeaderboard(game.players,game.players.length);start.disabled=game.phase==='question'||game.question_number>=game.question_count;results.disabled=game.phase!=='question';finish.disabled=game.phase==='finished'}}
start.onclick=async()=>{try{await api('start_question',{code});poll()}catch(e){alert(e.message)}};results.onclick=async()=>{try{await api('show_results',{code});poll()}catch(e){alert(e.message)}};finish.onclick=async()=>{try{await api('finish_game',{code});poll();loadHistory();loadStats()}catch(e){alert(e.message)}};reset.onclick=async()=>{if(!confirm(`Archive the current game and start a fresh game using code ${code}?`))return;try{await api('replay_game',{code});poll();loadHistory();loadStats()}catch(e){alert(e.message)}};logout.onclick=async()=>{await api('admin_logout');location.reload()};setInterval(poll,1000);if(<?= $logged?'true':'false' ?>)loadQuizzes();
</script></body></html>