<?php $code = preg_replace('/\D/','',$_GET['code'] ?? ''); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quiz Web Interactive Display</title><link rel="stylesheet" href="assets/app.css"></head><body class="display-body"><main class="shell"><div class="topbar"><h1>Quiz Web Interactive</h1><span class="pill" id="meta">Game <?=htmlspecialchars($code)?></span></div><section class="card" id="screen"><p class="status">Connecting…</p></section></main><script src="assets/app.js"></script><script>
const code=<?=json_encode($code)?>;let game,offset=0;
async function poll(){try{const r=await fetch(`api.php?action=state&display=1&code=${encodeURIComponent(code)}`,{cache:'no-store'});const j=await r.json();if(!j.ok)throw new Error(j.error);game=j.game;offset=game.server_time-Date.now()/1000;render()}catch(e){document.getElementById('screen').innerHTML=`<p class="status wrong">${escapeHtml(e.message)}</p>`}}
function renderPodium(players){if(!players.length)return '<p class="muted">No teams completed this game.</p>';const top=players.slice(0,3);return `<div class="podium">${top.map((p,i)=>`<div class="podium-place place-${i+1}"><div class="podium-rank">${i+1}</div><div class="podium-team"><i class="swatch" style="background:${p.color}"></i>${escapeHtml(p.team_name)}</div><strong>${p.score.toLocaleString()} pts</strong></div>`).join('')}</div>`}
function render(){const s=document.getElementById('screen');document.getElementById('meta').textContent=`Game ${game.code} • ${game.players.length} teams`;if(game.phase==='lobby'){s.innerHTML=`<p class="muted">Join at this site using game code</p><div class="code">${game.code}</div><h2>${escapeHtml(game.title)}</h2><h3>Teams joined</h3>${renderLeaderboard(game.players)}`;return}if(game.phase==='question'){const answered=game.players.filter(p=>p.answered_current).length;s.innerHTML=`<div class="timer" id="timer">30</div><div class="progress"><div id="bar"></div></div><p class="muted">Question ${game.question_number} of ${game.question_count} • ${answered}/${game.players.length} answered</p><h2 class="question">${escapeHtml(game.question.text)}</h2><div class="answer-grid">${game.question.choices.map(c=>`<div class="answer">${escapeHtml(c)}</div>`).join('')}</div>`;tick();return}if(game.phase==='results'){const q=game.question;s.innerHTML=`<p class="muted">Question ${game.question_number} result</p><h2 class="question">${escapeHtml(q.text)}</h2><p class="status correct">Correct answer: ${escapeHtml(q.choices[q.correct_index])}</p><h2>Current ranking</h2>${renderLeaderboard(game.players)}`;return}s.innerHTML=`<h2>Final results</h2>${renderPodium(game.players)}<h3>Full final ranking</h3>${renderLeaderboard(game.players,game.players.length)}`}
function tick(){if(!game||game.phase!=='question')return;const left=Math.max(0,game.ends_at-(Date.now()/1000+offset));const t=document.getElementById('timer'),b=document.getElementById('bar');if(t)t.textContent=Math.ceil(left);if(b)b.style.width=`${left/game.duration*100}%`;requestAnimationFrame(tick)}
poll();setInterval(poll,1000);
</script></body></html>
