/*
 * Ticketing - app.js
 * File Revision: 1.4.0
 * Modified: 2026-09-15
 *
 * Revision History:
 * 1.4.0 - Replaced long requester/category dropdown workflows with searchable autocomplete comboboxes and usage-aware suggestions.
 * 1.3.0 - Added hierarchical category loading, category references, and controlled category dropdown.
 * 1.1.1 - Added password confirmation fields and client-side matching validation for account creation.
 * 1.1.0 - Added passwordless test login, display-name profiles, avatar upload, and profile editing.
 * 1.0.0 - Added login flows, persistent requester/agent lists, add-new dropdown actions, and session-aware ticket access.
 */

const state={user:null,project:{},tickets:[],directory:[],categories:[],categoryTree:[],requesterView:'requesterDashboard',agentView:'agentDashboard',sort:{key:'updatedAt',direction:'desc'},loginRole:'requester',loginMode:'login',agentBootstrapAvailable:false,testMode:false};
const $=id=>document.getElementById(id);
const ticketDialog=$('ticketDialog'),personDialog=$('personDialog'),profileDialog=$('profileDialog');
const ticketForm=$('ticketForm'),personForm=$('personForm'),profileForm=$('profileForm');

(function loadAutocompleteStyles(){if(document.getElementById('ticketingAutocompleteCss'))return;const link=document.createElement('link');link.id='ticketingAutocompleteCss';link.rel='stylesheet';link.href='autocomplete.css?v=1.0.0';document.head.appendChild(link);})();

async function api(method='GET',body=null,action='tickets'){const r=await fetch(`index.php?api=1&action=${encodeURIComponent(action)}`,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):null});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed.');return d;}
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function ticketNumber(t){return `#${String(t.number||0).padStart(5,'0')}`;}
function prettyDate(v){return v?new Date(v).toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'';}
function badge(v){const c=String(v).toLowerCase().replace(/[^a-z0-9]+/g,'-');return `<span class="badge ${c}">${esc(v)}</span>`;}
function isAgent(){return state.user?.role==='agent';}
function avatarSrc(user){return user?.avatar||'';}
function avatarFallback(user){const n=(user?.displayName||user?.name||user?.email||'?').trim();return (n[0]||'?').toUpperCase();}
function paintAvatar(img,user){const src=avatarSrc(user);if(src){img.src=src;img.classList.remove('avatar-fallback');img.alt=user.displayName||user.email||'Profile';}else{img.removeAttribute('src');img.alt=avatarFallback(user);img.classList.add('avatar-fallback');img.dataset.initial=avatarFallback(user);}}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(file.size>2*1024*1024)return reject(new Error('Avatar must be 2 MB or smaller.'));const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(new Error('Could not read avatar file.'));reader.readAsDataURL(file);});}
function validateMatchingPasswords(password,confirmation){if(password!==confirmation)throw new Error('Password and confirmation password do not match.');if(password&&password.length<8)throw new Error('If a password is provided, it must be at least 8 characters.');}
function statHtml(ts){const c={Open:0,Pending:0,Resolved:0,Closed:0};ts.forEach(t=>{if(Object.hasOwn(c,t.status))c[t.status]++;});return [['Open',c.Open],['Pending',c.Pending],['Resolved',c.Resolved],['Closed',c.Closed],['Total',ts.length]].map(([l,n])=>`<div class="stat-card"><span>${l}</span><strong>${n}</strong></div>`).join('');}
function basicTable(ts,requester=false){if(!ts.length)return '<div class="empty-state">No tickets match this view.</div>';return `<div class="table-wrap"><table><thead><tr><th>Ticket</th>${requester?'':'<th>Requester</th>'}<th>Status</th><th>Priority</th><th>Agent</th><th>Updated</th></tr></thead><tbody>${ts.map(t=>`<tr class="ticket-row" data-id="${esc(t.id)}"><td><strong>${ticketNumber(t)}</strong><div class="ticket-subject">${esc(t.subject)}</div><div class="muted small">${esc(t.category||'General')}</div></td>${requester?'':`<td>${esc(t.requester)}<div class="muted small">${esc(t.email||'')}</div></td>`}<td>${badge(t.status||'Open')}</td><td>${badge(t.priority||'Medium')}</td><td>${esc(t.assignedTo||'Unassigned')}</td><td>${prettyDate(t.updatedAt)}</td></tr>`).join('')}</tbody></table></div>`;}
function sortVal(t,k){if(k==='number')return Number(t.number||0);if(k==='createdAt'||k==='updatedAt')return new Date(t[k]||0).getTime();return String(t[k]||'').toLowerCase();}
function agentTable(ts){if(!ts.length)return '<div class="empty-state">No tickets match this view.</div>';const {key,direction}=state.sort;const rows=[...ts].sort((a,b)=>{const av=sortVal(a,key),bv=sortVal(b,key),r=av<bv?-1:av>bv?1:0;return direction==='asc'?r:-r;});const h=(l,k)=>`<button class="sort-button" data-sort="${k}">${l}${key===k?(direction==='asc'?' ▲':' ▼'):''}</button>`;return `<div class="table-wrap"><table class="agent-table"><thead><tr><th>${h('Ticket','number')}</th><th>${h('Requester','requester')}</th><th>${h('Status','status')}</th><th>${h('Priority','priority')}</th><th>${h('Agent','assignedTo')}</th><th>${h('Created','createdAt')}</th><th>${h('Updated','updatedAt')}</th></tr></thead><tbody>${rows.map(t=>`<tr class="ticket-row" data-id="${esc(t.id)}"><td><strong>${ticketNumber(t)}</strong><div class="ticket-subject">${esc(t.subject)}</div><div class="muted small">${esc(t.category||'General')}</div></td><td>${esc(t.requester)}<div class="muted small">${esc(t.email||'')}</div></td><td>${badge(t.status||'Open')}</td><td>${badge(t.priority||'Medium')}</td><td>${esc(t.assignedTo||'Unassigned')}</td><td>${prettyDate(t.createdAt)}</td><td>${prettyDate(t.updatedAt)}</td></tr>`).join('')}</tbody></table></div>`;}
function bindRows(c){c.querySelectorAll('.ticket-row').forEach(r=>r.addEventListener('click',()=>openTicket(r.dataset.id)));}
function bindSort(){document.querySelectorAll('.sort-button').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const k=b.dataset.sort;state.sort=state.sort.key===k?{key:k,direction:state.sort.direction==='asc'?'desc':'asc'}:{key:k,direction:'asc'};renderAgentTickets();}));}
function requesterEntries(){return state.directory.filter(x=>x.role==='requester'&&x.active!==false).sort((a,b)=>(a.displayName||a.name||'').localeCompare(b.displayName||b.name||''));}
function agentEntries(){return state.directory.filter(x=>x.role==='agent'&&x.active!==false).sort((a,b)=>(a.displayName||a.name||'').localeCompare(b.displayName||b.name||''));}

function usageMap(kind){const map=new Map();for(const t of state.tickets){const key=kind==='requester'?String(t.email||'').toLowerCase():String(t.categoryId||'');if(!key)continue;const when=new Date(t.updatedAt||t.createdAt||0).getTime()||0;const current=map.get(key)||{count:0,last:0};current.count++;current.last=Math.max(current.last,when);map.set(key,current);}return map;}
function requesterSuggestions(query=''){const q=query.trim().toLowerCase(),usage=usageMap('requester');return requesterEntries().filter(x=>{const hay=`${x.displayName||x.name||''} ${x.email||''}`.toLowerCase();return !q||q.split(/\s+/).every(term=>hay.includes(term));}).sort((a,b)=>{if(q)return (a.displayName||a.name||'').localeCompare(b.displayName||b.name||'');const au=usage.get(String(a.email||'').toLowerCase())||{count:0,last:0},bu=usage.get(String(b.email||'').toLowerCase())||{count:0,last:0};return bu.count-au.count||bu.last-au.last||(a.displayName||a.name||'').localeCompare(b.displayName||b.name||'');}).slice(0,q?14:8);}
function categorySuggestions(query=''){const q=query.trim().toLowerCase(),usage=usageMap('category');return state.categories.filter(c=>{const hay=`${c.name||''} ${c.path||''}`.toLowerCase();return !q||q.split(/\s+/).every(term=>hay.includes(term));}).sort((a,b)=>{if(q){const an=String(a.name||'').toLowerCase(),bn=String(b.name||'').toLowerCase();const aStart=an.startsWith(q)?0:1,bStart=bn.startsWith(q)?0:1;return aStart-bStart||String(a.path||'').localeCompare(String(b.path||''));}const au=usage.get(String(a.id||''))||{count:0,last:0},bu=usage.get(String(b.id||''))||{count:0,last:0};if(a.id==='general'&&b.id!=='general')return -1;if(b.id==='general'&&a.id!=='general')return 1;return bu.count-au.count||bu.last-au.last||String(a.path||'').localeCompare(String(b.path||''));}).slice(0,q?16:10);}
function categoryDisplay(c){return c?.path||c?.name||'';}
function requesterDisplay(r){return r?`${r.displayName||r.name||r.email} — ${r.email}`:'';}
function comboParts(selectId){return {select:$(selectId),input:$(`${selectId}Search`),list:$(`${selectId}Suggestions`)};}
function renderCombo(selectId,query=''){const {select,input,list}=comboParts(selectId);if(!select||!input||!list)return;const isRequester=selectId==='requesterSelect';const items=isRequester?requesterSuggestions(query):categorySuggestions(query);let html='';if(!query)html+=`<div class="combo-heading">${isRequester?'Recent / frequently used':'Frequently used / common'}</div>`;if(items.length){html+=items.map((item,i)=>{if(isRequester)return `<button type="button" class="combo-option" data-combo-index="${i}" data-value="${esc(item.email)}"><span class="combo-primary">${esc(item.displayName||item.name||item.email)}</span><span class="combo-secondary">${esc(item.email||'')}</span></button>`;const path=String(item.path||item.name||'');const parts=path.split(' > ');const leaf=parts.pop()||path;const parent=parts.join(' › ');return `<button type="button" class="combo-option" data-combo-index="${i}" data-value="${esc(item.id)}"><span class="combo-primary">${esc(leaf)}</span>${parent?`<span class="combo-secondary">${esc(parent)}</span>`:''}</button>`;}).join('');}else html+='<div class="combo-empty">No matches</div>';
if(isRequester)html+='<button type="button" class="combo-option combo-action" data-value="__new__"><span class="combo-primary">+ Add new requester…</span></button>';list.innerHTML=html;list.classList.remove('hidden');list.dataset.active='-1';list.querySelectorAll('.combo-option').forEach(btn=>btn.addEventListener('mousedown',e=>{e.preventDefault();chooseCombo(selectId,btn.dataset.value);}));}
function chooseCombo(selectId,value){const {select,input,list}=comboParts(selectId);if(!select||!input)return;if(value==='__new__'&&selectId==='requesterSelect'){list?.classList.add('hidden');openPersonDialog('requester');return;}select.value=value;if(selectId==='requesterSelect'){const r=state.directory.find(x=>x.role==='requester'&&String(x.email)===value);input.value=requesterDisplay(r);$('email').value=r?.email||'';}else{const c=state.categories.find(x=>String(x.id)===value);input.value=categoryDisplay(c);}list?.classList.add('hidden');select.dispatchEvent(new Event('change',{bubbles:true}));}
function syncCombo(selectId){const {select,input}=comboParts(selectId);if(!select||!input)return;if(selectId==='requesterSelect'){const r=state.directory.find(x=>x.role==='requester'&&String(x.email)===String(select.value));input.value=requesterDisplay(r);}else{const c=state.categories.find(x=>String(x.id)===String(select.value));input.value=categoryDisplay(c);}input.disabled=select.disabled;}
function moveComboActive(selectId,delta){const {list}=comboParts(selectId);if(!list||list.classList.contains('hidden'))return;const options=[...list.querySelectorAll('.combo-option')];if(!options.length)return;let i=Number(list.dataset.active||-1);i=(i+delta+options.length)%options.length;options.forEach((o,n)=>o.classList.toggle('active',n===i));list.dataset.active=String(i);options[i].scrollIntoView({block:'nearest'});}
function initCombo(selectId,placeholder){const select=$(selectId);if(!select||select.dataset.comboReady)return;select.dataset.comboReady='1';select.classList.add('combo-native');const wrap=document.createElement('div');wrap.className='combobox';const input=document.createElement('input');input.type='search';input.id=`${selectId}Search`;input.className='combo-input';input.placeholder=placeholder;input.autocomplete='off';input.spellcheck=false;input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');const list=document.createElement('div');list.id=`${selectId}Suggestions`;list.className='combo-suggestions hidden';list.setAttribute('role','listbox');select.parentNode.insertBefore(wrap,select);wrap.appendChild(input);wrap.appendChild(select);wrap.appendChild(list);input.addEventListener('focus',()=>renderCombo(selectId,input.value));input.addEventListener('input',()=>{select.value='';renderCombo(selectId,input.value);});input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();if(list.classList.contains('hidden'))renderCombo(selectId,input.value);moveComboActive(selectId,1);}else if(e.key==='ArrowUp'){e.preventDefault();moveComboActive(selectId,-1);}else if(e.key==='Enter'&&!list.classList.contains('hidden')){const options=[...list.querySelectorAll('.combo-option')];const i=Number(list.dataset.active||-1);if(i>=0&&options[i]){e.preventDefault();chooseCombo(selectId,options[i].dataset.value);}}else if(e.key==='Escape'){list.classList.add('hidden');}});input.addEventListener('blur',()=>setTimeout(()=>{list.classList.add('hidden');if(!select.value)syncCombo(selectId);},140));syncCombo(selectId);}
function ensureTicketCombos(){initCombo('requesterSelect','Type requester name or email…');initCombo('category','Type any part of a category…');syncCombo('requesterSelect');syncCombo('category');}

function fillDirectorySelects(requesterEmail='',agentName=''){const rq=$('requesterSelect');rq.innerHTML='<option value="">Select requester...</option>'+requesterEntries().map(x=>`<option value="${esc(x.email)}">${esc(x.displayName||x.name)} — ${esc(x.email)}</option>`).join('')+'<option value="__new__">+ Add new requester...</option>';rq.value=[...rq.options].some(o=>o.value===requesterEmail)?requesterEmail:'';const ag=$('assignedTo');ag.innerHTML='<option value="">Unassigned</option>'+agentEntries().map(x=>`<option value="${esc(x.displayName||x.name)}">${esc(x.displayName||x.name)}</option>`).join('')+'<option value="__new__">+ Add new agent...</option>';ag.value=[...ag.options].some(o=>o.value===agentName)?agentName:'';const f=$('agentFilter'),cur=f.value;f.innerHTML='<option value="">All agents</option>'+agentEntries().map(x=>`<option value="${esc(x.displayName||x.name)}">${esc(x.displayName||x.name)}</option>`).join('');if([...f.options].some(o=>o.value===cur))f.value=cur;syncCombo('requesterSelect');}
function fillCategorySelect(selectedId='',legacyPath=''){const select=$('category');select.innerHTML=state.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.path)}</option>`).join('');let value=selectedId;if(!value&&legacyPath){const found=state.categories.find(c=>String(c.path).toLowerCase()===String(legacyPath).toLowerCase());value=found?.id||'';}if(!value||![...select.options].some(o=>o.value===value))value=state.categories.find(c=>c.id==='general')?.id||state.categories[0]?.id||'';select.value=value;syncCombo('category');}
function renderProject(){$('projectRevision').textContent=`Project rev ${state.project.revision||'--'}`;$('projectModified').textContent=`Modified ${state.project.modified||'--'}`;}
function renderRequesterDashboard(){$('requesterStats').innerHTML=statHtml(state.tickets);const r=[...state.tickets].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,8);$('requesterRecentTickets').innerHTML=basicTable(r,true);bindRows($('requesterRecentTickets'));}
function renderRequesterTickets(){const q=$('requesterSearchInput').value.trim().toLowerCase(),s=$('requesterStatusFilter').value;const t=state.tickets.filter(x=>(!s||x.status===s)&&(!q||[x.number,x.subject,x.description,x.category,x.assignedTo].join(' ').toLowerCase().includes(q)));$('myTicketList').innerHTML=basicTable(t,true);bindRows($('myTicketList'));}
function renderAgentDashboard(){$('agentStats').innerHTML=statHtml(state.tickets);const r=[...state.tickets].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,8);$('agentRecentTickets').innerHTML=basicTable(r);bindRows($('agentRecentTickets'));}
function renderAgentTickets(){const q=$('agentSearchInput').value.trim().toLowerCase(),s=$('agentStatusFilter').value,p=$('agentPriorityFilter').value,a=$('agentFilter').value;const t=state.tickets.filter(x=>(!s||x.status===s)&&(!p||x.priority===p)&&(!a||x.assignedTo===a)&&(!q||[x.number,x.subject,x.description,x.requester,x.email,x.category,x.assignedTo,x.source].join(' ').toLowerCase().includes(q)));$('agentTicketList').innerHTML=agentTable(t);bindRows($('agentTicketList'));bindSort();}
function updateVisible(){const a=isAgent();$('requesterNav').classList.toggle('hidden',a);$('agentNav').classList.toggle('hidden',!a);$('requesterDashboardView').classList.toggle('hidden',a||state.requesterView!=='requesterDashboard');$('myTicketsView').classList.toggle('hidden',a||state.requesterView!=='myTickets');$('agentDashboardView').classList.toggle('hidden',!a||state.agentView!=='agentDashboard');$('allTicketsView').classList.toggle('hidden',!a||state.agentView!=='allTickets');if(a){if(state.agentView==='agentDashboard'){$('pageTitle').textContent='Agent Dashboard';$('pageSubtitle').textContent='Queue overview across all requesters and agents.';renderAgentDashboard();}else{$('pageTitle').textContent='All Tickets';$('pageSubtitle').textContent='Search, sort, assign, and update every ticket.';renderAgentTickets();}}else{if(state.requesterView==='requesterDashboard'){$('pageTitle').textContent='My Dashboard';$('pageSubtitle').textContent='Track the tickets you submitted.';renderRequesterDashboard();}else{$('pageTitle').textContent='My Tickets';$('pageSubtitle').textContent='Your submitted requests and public replies.';renderRequesterTickets();}}}
function clearTicket(){ticketForm.reset();$('ticketId').value='';$('priority').value='Medium';$('status').value='Open';$('source').value='Portal';$('comment').value='';$('replySection').classList.add('hidden');$('commentHistory').classList.add('hidden');$('commentHistory').innerHTML='';document.querySelector('input[name="replyVisibility"][value="public"]').checked=true;fillDirectorySelects();fillCategorySelect('general');syncCombo('requesterSelect');syncCombo('category');}
function setFieldAccess(isNew){document.querySelectorAll('.agent-field').forEach(el=>el.classList.toggle('hidden',!isAgent()));['subject','priority','category','description'].forEach(id=>$(id).disabled=!isAgent()&&!isNew);['status','requesterSelect','email','assignedTo','source'].forEach(id=>$(id).disabled=!isAgent());syncCombo('requesterSelect');syncCombo('category');$('visibilityControl').classList.toggle('hidden',!isAgent());$('replyHint').textContent=isAgent()?'Public replies are visible to the requester. Private notes are agent-only.':'Your reply is public and visible to agents.';}
function openNewTicket(){clearTicket();setFieldAccess(true);$('ticketEyebrow').textContent='New ticket';$('dialogTitle').textContent=isAgent()?'Create Ticket':'Submit Ticket';$('saveButton').textContent=$('dialogTitle').textContent;ticketDialog.showModal();}
function renderComments(t){const cs=t.comments||[];if(!cs.length)return;$('commentHistory').classList.remove('hidden');$('commentHistory').innerHTML=`<h3>Conversation & Activity</h3>${[...cs].reverse().map(c=>`<div class="comment ${c.visibility||'public'}"><div><strong>${esc(c.author||'User')}</strong><span>${prettyDate(c.createdAt)}</span></div><div class="comment-meta"><span class="visibility ${c.visibility||'public'}">${c.visibility==='private'?'Private note':'Public'}</span></div><p>${esc(c.body)}</p></div>`).join('')}`;}
function openTicket(id){const t=state.tickets.find(x=>x.id===id);if(!t)return;clearTicket();setFieldAccess(false);$('ticketId').value=t.id;$('subject').value=t.subject||'';$('priority').value=t.priority||'Medium';$('status').value=t.status||'Open';fillCategorySelect(t.categoryId||'',t.category||'General');$('source').value=t.source||'Portal';$('description').value=t.description||'';$('email').value=t.email||'';fillDirectorySelects(t.email||'',t.assignedTo||'');$('ticketEyebrow').textContent=ticketNumber(t);$('dialogTitle').textContent=isAgent()?'Agent Ticket Details':'Ticket Details';$('saveButton').textContent=isAgent()?'Save Changes':'Send Reply';$('replySection').classList.remove('hidden');renderComments(t);ticketDialog.showModal();}
async function loadSession(){const d=await api('GET',null,'session');state.user=d.user||null;state.project=d.project||{};state.agentBootstrapAvailable=!!d.agentBootstrapAvailable;state.testMode=!!d.testMode;renderProject();$('testModeNotice').classList.toggle('hidden',!state.testMode);if(state.user)await enterApp();else showLogin();}
async function loadData(){const [t,d,c]=await Promise.all([api('GET',null,'tickets'),api('GET',null,'directory'),api('GET',null,'categories')]);state.tickets=t.tickets||[];state.project=t.project||state.project;state.directory=d.directory||[];state.categories=c.flat||[];state.categoryTree=c.categories||[];renderProject();ensureTicketCombos();fillDirectorySelects();fillCategorySelect('general');updateVisible();}
async function enterApp(){$('loginScreen').classList.add('hidden');$('appShell').classList.remove('hidden');$('signedInName').textContent=state.user.displayName||state.user.name||state.user.email;$('signedInRole').textContent=state.user.role;$('signedInEmail').textContent=state.user.email;paintAvatar($('signedInAvatar'),state.user);await loadData();}
function showLogin(){$('appShell').classList.add('hidden');$('loginScreen').classList.remove('hidden');setLoginMode('login');}
function setLoginMode(mode){state.loginMode=mode;const creating=mode!=='login';const showPassword=creating||!state.testMode;$('loginNameWrap').classList.toggle('hidden',!creating);$('loginAvatarWrap').classList.toggle('hidden',!creating);$('loginPasswordWrap').classList.toggle('hidden',!showPassword);$('loginPasswordConfirmWrap').classList.toggle('hidden',!creating);$('loginPassword').value='';$('loginPasswordConfirm').value='';$('loginSubmitButton').textContent=mode==='login'?'Sign in':mode==='registerRequester'?'Create requester account':'Create first agent account';$('registerRequesterButton').classList.toggle('hidden',mode!=='login'||state.loginRole!=='requester');$('bootstrapAgentButton').classList.toggle('hidden',mode!=='login'||state.loginRole!=='agent'||!state.agentBootstrapAvailable);$('backToLoginButton').classList.toggle('hidden',mode==='login');$('loginMessage').textContent='';}
function openPersonDialog(role){$('personRole').value=role;$('personDialogTitle').textContent=role==='agent'?'Add Agent':'Add Requester';personForm.reset();$('personRole').value=role;personDialog.showModal();}
function openProfile(){profileForm.reset();$('profileEmail').value=state.user.email||'';$('profileDisplayName').value=state.user.displayName||state.user.name||'';paintAvatar($('profileAvatarPreview'),state.user);profileDialog.showModal();}

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const creating=state.loginMode!=='login';const password=$('loginPassword').value;const passwordConfirm=creating?$('loginPasswordConfirm').value:password;if(creating)validateMatchingPasswords(password,passwordConfirm);const avatarData=state.loginMode==='login'?'':await fileToDataUrl($('loginAvatar').files[0]);const body={role:state.loginRole,displayName:$('loginName').value.trim(),email:$('loginEmail').value.trim(),password,passwordConfirm,avatarData};const action=state.loginMode==='registerRequester'?'register-requester':state.loginMode==='bootstrapAgent'?'bootstrap-agent':'login';const d=await api('POST',body,action);state.user=d.user;await enterApp();}catch(err){$('loginMessage').textContent=err.message;}});
document.querySelectorAll('[data-login-role]').forEach(b=>b.addEventListener('click',()=>{state.loginRole=b.dataset.loginRole;document.querySelectorAll('[data-login-role]').forEach(x=>x.classList.toggle('active',x===b));setLoginMode('login');}));
$('registerRequesterButton').addEventListener('click',()=>setLoginMode('registerRequester'));$('bootstrapAgentButton').addEventListener('click',()=>setLoginMode('bootstrapAgent'));$('backToLoginButton').addEventListener('click',()=>setLoginMode('login'));
$('logoutButton').addEventListener('click',async()=>{await api('POST',{},'logout');state.user=null;location.reload();});$('profileButton').addEventListener('click',openProfile);$('closeProfileDialogButton').addEventListener('click',()=>profileDialog.close());$('cancelProfileButton').addEventListener('click',()=>profileDialog.close());
profileForm.addEventListener('submit',async e=>{e.preventDefault();try{const avatarData=await fileToDataUrl($('profileAvatar').files[0]);const d=await api('PUT',{displayName:$('profileDisplayName').value.trim(),avatarData},'profile');state.user=d.user;profileDialog.close();await enterApp();}catch(err){alert(err.message);}});
personForm.addEventListener('submit',async e=>{e.preventDefault();try{const password=$('personPassword').value,passwordConfirm=$('personPasswordConfirm').value;validateMatchingPasswords(password,passwordConfirm);await api('POST',{role:$('personRole').value,displayName:$('personName').value.trim(),email:$('personEmail').value.trim(),password,passwordConfirm},'directory');personDialog.close();await loadData();}catch(err){alert(err.message);}});$('closePersonDialogButton').addEventListener('click',()=>personDialog.close());$('cancelPersonButton').addEventListener('click',()=>personDialog.close());
$('requesterSelect').addEventListener('change',()=>{if($('requesterSelect').value==='__new__'){openPersonDialog('requester');$('requesterSelect').value='';return;}const entry=state.directory.find(x=>x.role==='requester'&&x.email===$('requesterSelect').value);$('email').value=entry?.email||'';syncCombo('requesterSelect');});$('category').addEventListener('change',()=>syncCombo('category'));$('assignedTo').addEventListener('change',()=>{if($('assignedTo').value==='__new__'){openPersonDialog('agent');$('assignedTo').value='';}});
ticketForm.addEventListener('submit',async e=>{e.preventDefault();const id=$('ticketId').value;const selectedRequester=state.directory.find(x=>x.role==='requester'&&x.email===$('requesterSelect').value);const selectedCategory=state.categories.find(x=>x.id===$('category').value);if(isAgent()&&!selectedRequester){alert('Choose a requester from the suggestions.');$('requesterSelectSearch')?.focus();return;}if(!selectedCategory){alert('Choose a category from the suggestions.');$('categorySearch')?.focus();return;}const common={priority:$('priority').value,categoryId:$('category').value,category:selectedCategory?.path||'General',description:$('description').value.trim()};const body=id?{id,subject:$('subject').value.trim(),requester:selectedRequester?.displayName||selectedRequester?.name||'',email:$('email').value.trim(),status:$('status').value,assignedTo:$('assignedTo').value,source:$('source').value.trim()||'Portal',comment:$('comment').value.trim(),visibility:isAgent()?document.querySelector('input[name="replyVisibility"]:checked').value:'public',...common}:{subject:$('subject').value.trim(),requester:selectedRequester?.displayName||selectedRequester?.name||'',email:$('email').value.trim(),assignedTo:$('assignedTo').value,source:$('source').value.trim()||'Portal',...common};if(id&&!isAgent()&&!body.comment){alert('Enter a reply before submitting.');return;}try{await api(id?'PUT':'POST',body,'tickets');ticketDialog.close();await loadData();if(!id){if(isAgent())state.agentView='allTickets';else state.requesterView='myTickets';updateVisible();}}catch(err){alert(err.message);}});
document.querySelectorAll('[data-requester-view]').forEach(b=>b.addEventListener('click',()=>{state.requesterView=b.dataset.requesterView;document.querySelectorAll('[data-requester-view]').forEach(x=>x.classList.toggle('active',x===b));updateVisible();}));document.querySelectorAll('[data-agent-view]').forEach(b=>b.addEventListener('click',()=>{state.agentView=b.dataset.agentView;document.querySelectorAll('[data-agent-view]').forEach(x=>x.classList.toggle('active',x===b));updateVisible();}));
$('requesterNewTicketButton').addEventListener('click',openNewTicket);$('agentNewTicketButton').addEventListener('click',openNewTicket);$('refreshButton').addEventListener('click',loadData);$('closeDialogButton').addEventListener('click',()=>ticketDialog.close());$('cancelButton').addEventListener('click',()=>ticketDialog.close());$('requesterSearchInput').addEventListener('input',renderRequesterTickets);$('requesterStatusFilter').addEventListener('change',renderRequesterTickets);$('agentSearchInput').addEventListener('input',renderAgentTickets);$('agentStatusFilter').addEventListener('change',renderAgentTickets);$('agentPriorityFilter').addEventListener('change',renderAgentTickets);$('agentFilter').addEventListener('change',renderAgentTickets);
loadSession().catch(err=>{$('loginMessage').textContent=err.message;});
