<?php
/*
Filename: smart-404-admin-password.sample.php
Revision: 1.0.0
Description: Sample password-hash file for smart-404-admin.php.
Author: Jason Lamb (with help from Codex CLI)
Created Date: 2026-05-28
Modified Date: 2026-05-28
Changelog:
1.0.0 initial release
*/

// Replace this sample hash with one generated by password_hash('your-password', PASSWORD_DEFAULT).
return '$2y$10$replaceThisWithARealPasswordHash';
